import { Component, OnInit, Input } from '@angular/core';
import { ContactService } from '../../../../@core/backend/common/services/contact.service';
import { FormGroup, FormBuilder } from '@angular/forms';
import { Observable } from 'rxjs';
import { getNullableDateValue, getNullableDataValue } from '../../../../@core/utils/helpers';

@Component({
    selector: 'ngx-accounting-tab',
    templateUrl: './accounting-tab.component.html',
    styleUrls: ['./accounting-tab.component.scss'],
})
export class AccountingTabComponent implements OnInit {
    accountName: '';
    form: FormGroup;
    @Input() service: ContactService;
    @Input() data: Observable<any>;

    constructor(private fb: FormBuilder) { }

    ngOnInit() {
        this.form = this.initForm(this.fb);
        this.loadAccountTestData(this.form);
    }

    loadAccountTestData(form: FormGroup) {
        const data = {
            clientID: 'ClientID',
            caseAdmin: 'caseAdmin',
            accStatus: 'accStatus',
            retDate: new Date(),
            transferLL: new Date(),
            programType: 'Program Type',
            sourceType: 'Source Type',
            subSource: 'subSource',
            retainerType: 'Retainer Type',
            statDraft: 'Status of Draft',
            monthPmtDay: 'Monthly PMT Day',
            monthPMT: 'Monthly PMT Type',
            pmtAMTDue: 'Pmt Amt Due',
            lastPmtMade: new Date(),
            amtPaid: 'Amount Paid',
            nextPayDue: new Date(),
            nextPmtAmtDue: 'Next Payment Amount Due',
            payorDisc: 'Payor Disc',
            monthlyAccRev: new Date(),
            contactWClient: new Date(),
            monthlyNSF: 'NSF',
            skip: 'Skip',
            skipAmt: 'Skip Amount',
            clientIncome: 'Client Income',
            prevMort: 'Previous Mortgage',
            monthsBehind: 'Months Behind',
            pastResDue: 'Past Due Res',
            rule68Def: new Date(),
            payAmt1: 'Payment Amount',
            payAmt2: 'Payment Amount',
            payAmt3: 'Payment Amount',
            payAmt4: 'Payment Amount',
            initDueDate1: new Date(),
            initDueDate2: new Date(),
            initDueDate3: new Date(),
            initDueDate4: new Date(),
            initDatePaid1: new Date(),
            initDatePaid2: new Date(),
            initDatePaid3: new Date(),
            initDatePaid4: new Date(),
            payType1: 'Payment Type',
            payType2: 'Payment Type',
            payType3: 'Payment Type',
            payType4: 'Payment Type',
            accVer1: new Date(),
            accVer2: new Date(),
            accVer3: new Date(),
            accVer4: new Date(),
            paymentDue1: 'Payment Due',
            paymentDue2: 'Payment Due',
            paymentDue3: 'Payment Due',
            paymentDue4: 'Payment Due',
            paymentDue5: 'Payment Due',
            paymentDue6: 'Payment Due',
            paymentDue7: 'Payment Due',
            paymentDue8: 'Payment Due',
            paymentDue9: 'Payment Due',
            paymentDue10: 'Payment Due',
            paymentDue11: 'Payment Due',
            paymentDue12: 'Payment Due',
            dueDate1: new Date(),
            dueDate2: new Date(),
            dueDate3: new Date(),
            dueDate4: new Date(),
            dueDate5: new Date(),
            dueDate6: new Date(),
            dueDate7: new Date(),
            dueDate8: new Date(),
            dueDate9: new Date(),
            dueDate10: new Date(),
            dueDate11: new Date(),
            dueDate12: new Date(),
            paymentPaid1: 'Payment Paid',
            paymentPaid2: 'Payment Paid',
            paymentPaid3: 'Payment Paid',
            paymentPaid4: 'Payment Paid',
            paymentPaid5: 'Payment Paid',
            paymentPaid6: 'Payment Paid',
            paymentPaid7: 'Payment Paid',
            paymentPaid8: 'Payment Paid',
            paymentPaid9: 'Payment Paid',
            paymentPaid10: 'Payment Paid',
            paymentPaid11: 'Payment Paid',
            paymentPaid12: 'Payment Paid',
            datePaid1: new Date(),
            datePaid2: new Date(),
            datePaid3: new Date(),
            datePaid4: new Date(),
            datePaid5: new Date(),
            datePaid6: new Date(),
            datePaid7: new Date(),
            datePaid8: new Date(),
            datePaid9: new Date(),
            datePaid10: new Date(),
            datePaid11: new Date(),
            datePaid12: new Date(),
            Total: 'Total',
            netTotal: 'Net Total',

            nsfA1: 'Firm Paid',
            nsfA2: 'Firm Paid',
            nsfA3: 'Firm Paid',
            nsfA4: 'Firm Paid',
            nsfA5: 'Firm Paid',
            nsfA6: 'Firm Paid',
            nsfA7: 'Firm Paid',
            nsfA8: 'Firm Paid',
            nsfA9: 'Firm Paid',
            nsfA10: 'Firm Paid',
            nsfA11: 'Firm Paid',
            nsfA12: 'Firm Paid',
            nsf1: 'NSF',
            nsf2: 'NSF',
            nsf3: 'NSF',
            nsf4: 'NSF',
            nsf5: 'NSF',
            nsf6: 'NSF',
            nsf7: 'NSF',
            nsf8: 'NSF',
            nsf9: 'NSF',
            nsf10: 'NSF',
            nsf11: 'NSF',
            nsf12: 'NSF',
            total2: 'Total',
            netTotal2: 'Net Total',
            aDueDate1: new Date(),
            aDueDate2: new Date(),
            aDueDate3: new Date(),
            aDueDate4: new Date(),
            aDueDate5: new Date(),
            aDueDate6: new Date(),
            aDueDate7: new Date(),
            aDueDate8: new Date(),
            aDueDate9: new Date(),
            aDueDate10: new Date(),
            aDueDate11: new Date(),
            aDueDate12: new Date(),
            costDesc1: 'Cost Description',
            costDesc2: 'Cost Description',
            costDesc3: 'Cost Description',
            costDesc4: 'Cost Description',
            costDesc5: 'Cost Description',
            costDesc6: 'Cost Description',
            costDesc7: 'Cost Description',
            costDesc8: 'Cost Description',
            costDesc9: 'Cost Description',
            costDesc10: 'Cost Description',
            costDesc11: 'Cost Description',
            costDesc12: 'Cost Description',
            cost1: 'Cost',
            cost2: 'Cost',
            cost3: 'Cost',
            cost4: 'Cost',
            cost5: 'Cost',
            cost6: 'Cost',
            cost7: 'Cost',
            cost8: 'Cost',
            cost9: 'Cost',
            cost10: 'Cost',
            cost11: 'Cost',
            cost12: 'Cost',
            payor1: 'Payor',
            payor2: 'Payor',
            payor3: 'Payor',
            payor4: 'Payor',
            payor5: 'Payor',
            payor6: 'Payor',
            purpFund1: 'Purpose of Fund',
            purpFund2: 'Purpose of Fund',
            purpFund3: 'Purpose of Fund',
            purpFund4: 'Purpose of Fund',
            purpFund5: 'Purpose of Fund',
            purpFund6: 'Purpose of Fund',
            amt1: 'Amount',
            amt2: 'Amount',
            amt3: 'Amount',
            amt4: 'Amount',
            amt5: 'Amount',
            amt6: 'Amount',
            date1: new Date(),
            date2: new Date(),
            date3: new Date(),
            date4: new Date(),
            date5: new Date(),
            date6: new Date(),
            payee1: 'Payee',
            payee2: 'Payee',
            payee3: 'Payee',
            payee4: 'Payee',
            payee5: 'Payee',
            payee6: 'Payee',
            purpFund7: 'Purpose of Fund',
            purpFund8: 'Purpose of Fund',
            purpFund9: 'Purpose of Fund',
            purpFund10: 'Purpose of Fund',
            purpFund11: 'Purpose of Fund',
            purpFund12: 'Purpose of Fund',
            amt7: 'Amount',
            amt8: 'Amount',
            amt9: 'Amount',
            amt10: 'Amount',
            amt11: 'Amount',
            amt12: 'Amount',
            date7: new Date(),
            date8: new Date(),
            date9: new Date(),
            date10: new Date(),
            date11: new Date(),
            date12: new Date(),
            total3: 'Total',





        };
        this.setFormValues(form, data);
    }

    initForm(fb: FormBuilder): FormGroup {

        const form = fb.group({
            rule68Def: fb.control(''),
            clientID: fb.control(''),
            caseAdmin: fb.control(''),
            accStatus: fb.control(''),
            retDate: fb.control(''),
            transferLL: fb.control(''),
            programType: fb.control(''),
            sourceType: fb.control(''),
            subSource: fb.control(''),
            retainerType: fb.control(''),
            total3: fb.control(''),
            statDraft: fb.control(''),
            monthPmtDay: fb.control(''),
            monthPMT: fb.control(''),
            pmtAMTDue: fb.control(''),
            lastPmtMade: fb.control(''),
            amtPaid: fb.control(''),
            nextPayDue: fb.control(''),
            nextPmtAmtDue: fb.control(''),
            payorDisc: fb.control(''),
            monthlyAccRev: fb.control(''),
            contactWClient: fb.control(''),
            monthlyNSF: fb.control(''),
            skip: fb.control(''),
            skipAmt: fb.control(''),
            clientIncome: fb.control(''),
            prevMort: fb.control(''),
            monthsBehind: fb.control(''),
            pastResDue: fb.control(''),
            payAmt1: fb.control(''),
            payAmt2: fb.control(''),
            payAmt3: fb.control(''),
            payAmt4: fb.control(''),
            payor1: fb.control(''),
            payor2: fb.control(''),
            payor3: fb.control(''),
            payor4: fb.control(''),
            payor5: fb.control(''),
            payor6: fb.control(''),
            initDueDate1: fb.control(''),
            initDueDate2: fb.control(''),
            initDueDate3: fb.control(''),
            initDueDate4: fb.control(''),
            payType1: fb.control(''),
            payType2: fb.control(''),
            payType3: fb.control(''),
            payType4: fb.control(''),
            accVer1: fb.control(''),
            accVer2: fb.control(''),
            accVer3: fb.control(''),
            accVer4: fb.control(''),
            initDatePaid1: fb.control(''),
            initDatePaid2: fb.control(''),
            initDatePaid3: fb.control(''),
            initDatePaid4: fb.control(''),
            nsf1: fb.control(''),
            nsf2: fb.control(''),
            nsf3: fb.control(''),
            nsf4: fb.control(''),
            nsf5: fb.control(''),
            nsf6: fb.control(''),
            nsf7: fb.control(''),
            nsf8: fb.control(''),
            nsf9: fb.control(''),
            nsf10: fb.control(''),
            nsf11: fb.control(''),
            nsf12: fb.control(''),
            netTotal2: fb.control(''),
            netTotal: fb.control(''),
            total: fb.control(''),
            total2: fb.control(''),
            paymentDue1: fb.control(''),
            paymentDue2: fb.control(''),
            paymentDue3: fb.control(''),
            paymentDue4: fb.control(''),
            paymentDue5: fb.control(''),
            paymentDue6: fb.control(''),
            paymentDue7: fb.control(''),
            paymentDue8: fb.control(''),
            paymentDue9: fb.control(''),
            paymentDue10: fb.control(''),
            paymentDue11: fb.control(''),
            paymentDue12: fb.control(''),
            dueDate1: fb.control(''),
            dueDate2: fb.control(''),
            dueDate3: fb.control(''),
            dueDate4: fb.control(''),
            dueDate5: fb.control(''),
            dueDate6: fb.control(''),
            dueDate7: fb.control(''),
            dueDate8: fb.control(''),
            dueDate9: fb.control(''),
            dueDate10: fb.control(''),
            dueDate11: fb.control(''),
            dueDate12: fb.control(''),
            paymentPaid1: fb.control(''),
            paymentPaid2: fb.control(''),
            paymentPaid3: fb.control(''),
            paymentPaid4: fb.control(''),
            paymentPaid5: fb.control(''),
            paymentPaid6: fb.control(''),
            paymentPaid7: fb.control(''),
            paymentPaid8: fb.control(''),
            paymentPaid9: fb.control(''),
            paymentPaid10: fb.control(''),
            paymentPaid11: fb.control(''),
            paymentPaid12: fb.control(''),
            datePaid1: fb.control(''),
            datePaid2: fb.control(''),
            datePaid3: fb.control(''),
            datePaid4: fb.control(''),
            datePaid5: fb.control(''),
            datePaid6: fb.control(''),
            datePaid7: fb.control(''),
            datePaid8: fb.control(''),
            datePaid9: fb.control(''),
            datePaid10: fb.control(''),
            datePaid11: fb.control(''),
            datePaid12: fb.control(''),

            nsfA1: fb.control(''),
            nsfA2: fb.control(''),
            nsfA3: fb.control(''),
            nsfA4: fb.control(''),
            nsfA5: fb.control(''),
            nsfA6: fb.control(''),
            nsfA7: fb.control(''),
            nsfA8: fb.control(''),
            nsfA9: fb.control(''),
            nsfA10: fb.control(''),
            nsfA11: fb.control(''),
            nsfA12: fb.control(''),
            aDueDate1: fb.control(''),
            aDueDate2: fb.control(''),
            aDueDate3: fb.control(''),
            aDueDate4: fb.control(''),
            aDueDate5: fb.control(''),
            aDueDate6: fb.control(''),
            aDueDate7: fb.control(''),
            aDueDate8: fb.control(''),
            aDueDate9: fb.control(''),
            aDueDate10: fb.control(''),
            aDueDate11: fb.control(''),
            aDueDate12: fb.control(''),
            costDesc1: fb.control(''),
            costDesc2: fb.control(''),
            costDesc3: fb.control(''),
            costDesc4: fb.control(''),
            costDesc5: fb.control(''),
            costDesc6: fb.control(''),
            costDesc7: fb.control(''),
            costDesc8: fb.control(''),
            costDesc9: fb.control(''),
            costDesc10: fb.control(''),
            costDesc11: fb.control(''),
            costDesc12: fb.control(''),
            cost1: fb.control(''),
            cost2: fb.control(''),
            cost3: fb.control(''),
            cost4: fb.control(''),
            cost5: fb.control(''),
            cost6: fb.control(''),
            cost7: fb.control(''),
            cost8: fb.control(''),
            cost9: fb.control(''),
            cost10: fb.control(''),
            cost11: fb.control(''),
            cost12: fb.control(''),
            purpFund1: fb.control(''),
            purpFund2: fb.control(''),
            purpFund3: fb.control(''),
            purpFund4: fb.control(''),
            purpFund5: fb.control(''),
            purpFund6: fb.control(''),
            amt1: fb.control(''),
            amt2: fb.control(''),
            amt3: fb.control(''),
            amt4: fb.control(''),
            amt5: fb.control(''),
            amt6: fb.control(''),
            date1: fb.control(''),
            date2: fb.control(''),
            date3: fb.control(''),
            date4: fb.control(''),
            date5: fb.control(''),
            date6: fb.control(''),
            payee1: fb.control(''),
            payee2: fb.control(''),
            payee3: fb.control(''),
            payee4: fb.control(''),
            payee5: fb.control(''),
            payee6: fb.control(''),
            purpFund7: fb.control(''),
            purpFund8: fb.control(''),
            purpFund9: fb.control(''),
            purpFund10: fb.control(''),
            purpFund11: fb.control(''),
            purpFund12: fb.control(''),
            amt7: fb.control(''),
            amt8: fb.control(''),
            amt9: fb.control(''),
            amt10: fb.control(''),
            amt11: fb.control(''),
            amt12: fb.control(''),
            date7: fb.control(''),
            date8: fb.control(''),
            date9: fb.control(''),
            date10: fb.control(''),
            date11: fb.control(''),
            date12: fb.control(''),








        }, { updateOn: 'blur' });
        return form;
    }

    setFormValues(form: FormGroup, data: any) {
        form.setValue({
            rule68Def: getNullableDateValue(data.rule68Def, ''),
            clientID: getNullableDataValue(data.clientID, ''),
            monthlyNSF: getNullableDataValue(data.monthlyNSF, ''),
            caseAdmin: getNullableDataValue(data.caseAdmin, ''),
            accStatus: getNullableDataValue(data.accStatus, ''),
            retDate: getNullableDateValue(data.retDate, ''),
            transferLL: getNullableDateValue(data.transferLL, ''),
            programType: getNullableDataValue(data.programType, ''),
            sourceType: getNullableDataValue(data.sourceType, ''),
            subSource: getNullableDataValue(data.subSource, ''),
            retainerType: getNullableDataValue(data.retainerType, ''),
            statDraft: getNullableDataValue(data.statDraft, ''),
            monthPmtDay: getNullableDataValue(data.monthPmtDay, ''),
            monthPMT: getNullableDataValue(data.monthPMT, ''),
            pmtAMTDue: getNullableDataValue(data.pmtAMTDue, ''),
            lastPmtMade: getNullableDateValue(data.lastPmtMade, ''),
            amtPaid: getNullableDataValue(data.amtPaid, ''),
            nextPayDue: getNullableDateValue(data.nextPayDue, ''),
            nextPmtAmtDue: getNullableDataValue(data.nextPmtAmtDue, ''),
            payorDisc: getNullableDataValue(data.payorDisc, ''),
            monthlyAccRev: getNullableDateValue(data.monthlyAccRev, ''),
            contactWClient: getNullableDateValue(data.contactWClient, ''),
            skip: getNullableDataValue(data.skip, ''),
            skipAmt: getNullableDataValue(data.skipAmt, ''),
            clientIncome: getNullableDataValue(data.clientIncome, ''),
            prevMort: getNullableDataValue(data.prevMort, ''),
            monthsBehind: getNullableDataValue(data.monthsBehind, ''),
            pastResDue: getNullableDataValue(data.pastResDue, ''),
            payAmt1: getNullableDataValue(data.payAmt1, ''),
            payAmt2: getNullableDataValue(data.payAmt2, ''),
            payAmt3: getNullableDataValue(data.payAmt3, ''),
            payAmt4: getNullableDataValue(data.payAmt4, ''),
            initDueDate1: getNullableDateValue(data.initDueDate1, ''),
            initDueDate2: getNullableDateValue(data.initDueDate2, ''),
            initDueDate3: getNullableDateValue(data.initDueDate3, ''),
            initDueDate4: getNullableDateValue(data.initDueDate4, ''),
            initDatePaid1: getNullableDateValue(data.initDatePaid1, ''),
            initDatePaid2: getNullableDateValue(data.initDatePaid2, ''),
            initDatePaid3: getNullableDateValue(data.initDatePaid3, ''),
            initDatePaid4: getNullableDateValue(data.initDatePaid4, ''),
            payType1: getNullableDataValue(data.payType1, ''),
            payType2: getNullableDataValue(data.payType2, ''),
            payType3: getNullableDataValue(data.payType3, ''),
            payType4: getNullableDataValue(data.payType4, ''),
            accVer1: getNullableDataValue(data.accVer1, ''),
            accVer2: getNullableDataValue(data.accVer1, ''),
            accVer3: getNullableDataValue(data.accVer1, ''),
            accVer4: getNullableDataValue(data.accVer1, ''),
            payor1: getNullableDataValue(data.payor1, ''),
            payor2: getNullableDataValue(data.payor2, ''),
            payor3: getNullableDataValue(data.payor3, ''),
            payor4: getNullableDataValue(data.payor4, ''),
            payor5: getNullableDataValue(data.payor5, ''),
            payor6: getNullableDataValue(data.payor6, ''),
            purpFund1: getNullableDataValue(data.purpFund1, ''),
            purpFund2: getNullableDataValue(data.purpFund2, ''),
            purpFund3: getNullableDataValue(data.purpFund3, ''),
            purpFund4: getNullableDataValue(data.purpFund4, ''),
            purpFund5: getNullableDataValue(data.purpFund5, ''),
            purpFund6: getNullableDataValue(data.purpFund6, ''),
            amt1: getNullableDataValue(data.amt1, ''),
            amt2: getNullableDataValue(data.amt2, ''),
            amt3: getNullableDataValue(data.amt3, ''),
            amt4: getNullableDataValue(data.amt4, ''),
            amt5: getNullableDataValue(data.amt5, ''),
            amt6: getNullableDataValue(data.amt6, ''),
            date1: getNullableDataValue(data.date1, ''),
            date2: getNullableDataValue(data.date2, ''),
            date3: getNullableDataValue(data.date3, ''),
            date4: getNullableDataValue(data.date4, ''),
            date5: getNullableDataValue(data.date5, ''),
            date6: getNullableDataValue(data.date6, ''),
            payee1: getNullableDataValue(data.payee1, ''),
            payee2: getNullableDataValue(data.payee2, ''),
            payee3: getNullableDataValue(data.payee3, ''),
            payee4: getNullableDataValue(data.payee4, ''),
            payee5: getNullableDataValue(data.payee5, ''),
            payee6: getNullableDataValue(data.payee6, ''),
            purpFund7: getNullableDataValue(data.purpFund1, ''),
            purpFund8: getNullableDataValue(data.purpFund2, ''),
            purpFund9: getNullableDataValue(data.purpFund3, ''),
            purpFund10: getNullableDataValue(data.purpFund4, ''),
            purpFund11: getNullableDataValue(data.purpFund5, ''),
            purpFund12: getNullableDataValue(data.purpFund6, ''),
            amt7: getNullableDataValue(data.amt1, ''),
            amt8: getNullableDataValue(data.amt2, ''),
            amt9: getNullableDataValue(data.amt3, ''),
            amt10: getNullableDataValue(data.amt4, ''),
            amt11: getNullableDataValue(data.amt5, ''),
            amt12: getNullableDataValue(data.amt6, ''),
            date7: getNullableDataValue(data.date1, ''),
            date8: getNullableDataValue(data.date2, ''),
            date9: getNullableDataValue(data.date3, ''),
            date10: getNullableDataValue(data.date4, ''),
            date11: getNullableDataValue(data.date5, ''),
            date12: getNullableDataValue(data.date6, ''),
            total2: getNullableDataValue(data.total2, ''),
            total3: getNullableDataValue(data.total3, ''),
            nsf1: getNullableDataValue(data.nsf1, ''),
            nsf2: getNullableDataValue(data.nsf2, ''),
            nsf3: getNullableDataValue(data.nsf3, ''),
            nsf4: getNullableDataValue(data.nsf4, ''),
            nsf5: getNullableDataValue(data.nsf5, ''),
            nsf6: getNullableDataValue(data.nsf6, ''),
            nsf7: getNullableDataValue(data.nsf7, ''),
            nsf8: getNullableDataValue(data.nsf8, ''),
            nsf9: getNullableDataValue(data.nsf9, ''),
            nsf10: getNullableDataValue(data.nsf10, ''),
            nsf11: getNullableDataValue(data.nsf11, ''),
            nsf12: getNullableDataValue(data.nsf12, ''),
            total: getNullableDataValue(data.total, ''),

            netTotal2: getNullableDataValue(data.netTotal2, ''),
            netTotal: getNullableDataValue(data.netTotal, ''),

            paymentDue1: getNullableDataValue(data.paymentDue1, ''),
            paymentDue2: getNullableDataValue(data.paymentDue2, ''),
            paymentDue3: getNullableDataValue(data.paymentDue3, ''),
            paymentDue4: getNullableDataValue(data.paymentDue4, ''),
            paymentDue5: getNullableDataValue(data.paymentDue5, ''),
            paymentDue6: getNullableDataValue(data.paymentDue6, ''),
            paymentDue7: getNullableDataValue(data.paymentDue7, ''),
            paymentDue8: getNullableDataValue(data.paymentDue8, ''),
            paymentDue9: getNullableDataValue(data.paymentDue9, ''),
            paymentDue10: getNullableDataValue(data.paymentDue10, ''),
            paymentDue11: getNullableDataValue(data.paymentDue11, ''),
            paymentDue12: getNullableDataValue(data.paymentDue12, ''),
            dueDate1: getNullableDateValue(data.dueDate1, ''),
            dueDate2: getNullableDateValue(data.dueDate2, ''),
            dueDate3: getNullableDateValue(data.dueDate3, ''),
            dueDate4: getNullableDateValue(data.dueDate4, ''),
            dueDate5: getNullableDateValue(data.dueDate5, ''),
            dueDate6: getNullableDateValue(data.dueDate6, ''),
            dueDate7: getNullableDateValue(data.dueDate7, ''),
            dueDate8: getNullableDateValue(data.dueDate8, ''),
            dueDate9: getNullableDateValue(data.dueDate9, ''),
            dueDate10: getNullableDateValue(data.dueDate10, ''),
            dueDate11: getNullableDateValue(data.dueDate11, ''),
            dueDate12: getNullableDateValue(data.dueDate12, ''),
            paymentPaid1: getNullableDataValue(data.paymentPaid1, ''),
            paymentPaid2: getNullableDataValue(data.paymentPaid2, ''),
            paymentPaid3: getNullableDataValue(data.paymentPaid3, ''),
            paymentPaid4: getNullableDataValue(data.paymentPaid4, ''),
            paymentPaid5: getNullableDataValue(data.paymentPaid5, ''),
            paymentPaid6: getNullableDataValue(data.paymentPaid6, ''),
            paymentPaid7: getNullableDataValue(data.paymentPaid7, ''),
            paymentPaid8: getNullableDataValue(data.paymentPaid8, ''),
            paymentPaid9: getNullableDataValue(data.paymentPaid9, ''),
            paymentPaid10: getNullableDataValue(data.paymentPaid10, ''),
            paymentPaid11: getNullableDataValue(data.paymentPaid11, ''),
            paymentPaid12: getNullableDataValue(data.paymentPaid12, ''),
            datePaid1: getNullableDateValue(data.datePaid1, ''),
            datePaid2: getNullableDateValue(data.datePaid2, ''),
            datePaid3: getNullableDateValue(data.datePaid3, ''),
            datePaid4: getNullableDateValue(data.datePaid4, ''),
            datePaid5: getNullableDateValue(data.datePaid5, ''),
            datePaid6: getNullableDateValue(data.datePaid6, ''),
            datePaid7: getNullableDateValue(data.datePaid7, ''),
            datePaid8: getNullableDateValue(data.datePaid8, ''),
            datePaid9: getNullableDateValue(data.datePaid9, ''),
            datePaid10: getNullableDateValue(data.datePaid10, ''),
            datePaid11: getNullableDateValue(data.datePaid11, ''),
            datePaid12: getNullableDateValue(data.datePaid12, ''),

            nsfA1: getNullableDataValue(data.firmPaid1, ''),
            nsfA2: getNullableDataValue(data.firmPaid2, ''),
            nsfA3: getNullableDataValue(data.firmPaid3, ''),
            nsfA4: getNullableDataValue(data.firmPaid4, ''),
            nsfA5: getNullableDataValue(data.firmPaid5, ''),
            nsfA6: getNullableDataValue(data.firmPaid6, ''),
            nsfA7: getNullableDataValue(data.firmPaid7, ''),
            nsfA8: getNullableDataValue(data.firmPaid8, ''),
            nsfA9: getNullableDataValue(data.firmPaid9, ''),
            nsfA10: getNullableDataValue(data.firmPaid10, ''),
            nsfA11: getNullableDataValue(data.firmPaid11, ''),
            nsfA12: getNullableDataValue(data.firmPaid12, ''),
            aDueDate1: getNullableDateValue(data.aDueDate1, ''),
            aDueDate2: getNullableDateValue(data.aDueDate2, ''),
            aDueDate3: getNullableDateValue(data.aDueDate3, ''),
            aDueDate4: getNullableDateValue(data.aDueDate4, ''),
            aDueDate5: getNullableDateValue(data.aDueDate5, ''),
            aDueDate6: getNullableDateValue(data.aDueDate6, ''),
            aDueDate7: getNullableDateValue(data.aDueDate7, ''),
            aDueDate8: getNullableDateValue(data.aDueDate8, ''),
            aDueDate9: getNullableDateValue(data.aDueDate9, ''),
            aDueDate10: getNullableDateValue(data.aDueDate10, ''),
            aDueDate11: getNullableDateValue(data.aDueDate11, ''),
            aDueDate12: getNullableDateValue(data.aDueDate12, ''),
            costDesc1: getNullableDataValue(data.costDesc1, ''),
            costDesc2: getNullableDataValue(data.costDesc1, ''),
            costDesc3: getNullableDataValue(data.costDesc1, ''),
            costDesc4: getNullableDataValue(data.costDesc1, ''),
            costDesc5: getNullableDataValue(data.costDesc1, ''),
            costDesc6: getNullableDataValue(data.costDesc1, ''),
            costDesc7: getNullableDataValue(data.costDesc1, ''),
            costDesc8: getNullableDataValue(data.costDesc1, ''),
            costDesc9: getNullableDataValue(data.costDesc1, ''),
            costDesc10: getNullableDataValue(data.costDesc1, ''),
            costDesc11: getNullableDataValue(data.costDesc1, ''),
            costDesc12: getNullableDataValue(data.costDesc1, ''),
            cost1: getNullableDataValue(data.cost1, ''),
            cost2: getNullableDataValue(data.cost2, ''),
            cost3: getNullableDataValue(data.cost3, ''),
            cost4: getNullableDataValue(data.cost4, ''),
            cost5: getNullableDataValue(data.cost5, ''),
            cost6: getNullableDataValue(data.cost6, ''),
            cost7: getNullableDataValue(data.cost7, ''),
            cost8: getNullableDataValue(data.cost8, ''),
            cost9: getNullableDataValue(data.cost9, ''),
            cost10: getNullableDataValue(data.cost10, ''),
            cost11: getNullableDataValue(data.cost11, ''),
            cost12: getNullableDataValue(data.cost12, ''),








        });

    }
}
