import { Component, OnInit, Input } from '@angular/core';
import { ContactService } from '../../../../@core/backend/common/services/contact.service';
import { FormGroup, FormBuilder } from '@angular/forms';
import { Observable, Subject } from 'rxjs';
import { getNullableDataValue, getNullableDateValue } from '../../../../@core/utils/helpers';
import { OpportunityService } from '../../../../@core/backend/common/services/opportunity.service';
import { takeUntil } from 'rxjs/operators';
import { CustomValidator } from '../../../../@core/backend/common/services/validation.service';

@Component({
  selector: 'ngx-settlement-tab',
  templateUrl: './settlement-tab.component.html',
  styleUrls: ['./settlement-tab.component.scss'],
})
export class SettlementTabComponent implements OnInit {
  protected readonly unsubscribe$ = new Subject<void>();
  data: Observable<any>;
  form: FormGroup;
  @Input() service: OpportunityService;
  @Input() id: string;


  constructor(private fb: FormBuilder) { }

  ngOnInit() {
    this.form = this.initForm(this.fb);
    this.data = this.service.getSettlementAda(this.id).pipe(takeUntil(this.unsubscribe$));
    this.data.subscribe(d => {
      this.setFormValues(this.form, d, this.service);
    })
  }

  private setIntakeFormData(opportunityId: String) {
    return {
      ClientID: {
        table: 'Opportunity',
        column: 'ClientID',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      TCPA_State: {
        table: 'Law',
        column: 'TCPA_State',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      Party4Name: {
        table: 'Parties_Involved',
        column: 'Party4Name',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      Defendant1Long: {
        table: 'Parties_Involved',
        column: 'Defendant1Long',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      Party4Title: {
        table: 'Parties_Involved',
        column: 'Party4Title',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      Party4phone: {
        table: 'Parties_Involved',
        column: 'Party4phone',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      Party4email: {
        table: 'Parties_Involved',
        column: 'Party4email',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      Party1Co: {
        table: 'Parties_Involved',
        column: 'Party1Co',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      Party1Name: {
        table: 'Parties_Involved',
        column: 'Party1Name',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      Party1phone: {
        table: 'Parties_Involved',
        column: 'Party1phone',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      Party1direct: {
        table: 'Parties_Involved',
        column: 'Party1direct',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      Party1email: {
        table: 'Parties_Involved',
        column: 'Party1email',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      PlaintiffPhoneAcquire: {
        table: 'Law',
        column: 'PlaintiffPhoneAcquire',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      CRED1PROOF: {
        table: 'Law',
        column: 'CRED1PROOF',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      Advisor2: {
        table: 'Opportunity',
        column: 'Advisor2',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      Party2Co: {
        table: 'Parties_Involved',
        column: 'Party2Co',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      Party2Name: {
        table: 'Parties_Involved',
        column: 'Party2Name',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      Party2phone: {
        table: 'Parties_Involved',
        column: 'Party2phone',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      Party2direct: {
        table: 'Parties_Involved',
        column: 'Party2direct',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      Party2email: {
        table: 'Parties_Involved',
        column: 'Party2email',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      PMTDeclaration1: {
        table: 'Law',
        column: 'PMTDeclaration1',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      CRED2PROOF: {
        table: 'Law',
        column: 'CRED2PROOF',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      RecvdSettlOPC: {
        table: 'ADA',
        column: 'RecvdSettlOPC',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      misc1disc: {
        table: 'DebtorExpenses',
        column: 'misc1disc',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      InitialContactOPC: {
        table: 'ADA',
        column: 'InitialContactOPC',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      LegalAssistant2: {
        table: 'Parties_Involved',
        column: 'LegalAssistant2',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      misc2disc: {
        table: 'DebtorExpenses',
        column: 'misc2disc',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      SARDate: {
        table: 'ADA',
        column: 'SARDate',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      PaymentReceived: {
        table: 'ADA',
        column: 'PaymentReceived',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      drafted68: {
        table: 'CaseInfo',
        column: 'drafted68',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      Rule68: {
        table: 'CaseInfo',
        column: 'Rule68Amt',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      Rule68Amt: {
        table: 'CaseInfo',
        column: 'Rule68Amt',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      Rule68Offersent: {
        table: 'CaseInfo',
        column: 'Rule68Offersent',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      Rule68DefRespDue: {
        table: 'CaseInfo',
        column: 'Rule68DefRespDue',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      InitialDemand: {
        table: 'ADA',
        column: 'InitialDemand',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      InitialDemandDate: {
        table: 'ADA',
        column: 'InitialDemandDate',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      InitialOffer: {
        table: 'ADA',
        column: 'InitialOffer',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      InitialOfferDate: {
        table: 'ADA',
        column: 'InitialOfferDate',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      CounterSettl: {
        table: 'ADA',
        column: 'CounterSettl',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      CounterSettlDate: {
        table: 'ADA',
        column: 'CounterSettlDate',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ProposedSettl: {
        table: 'ADA',
        column: 'ProposedSettl',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      PROPOSEDSETTLDATE: {
        table: 'ADA',
        column: 'PROPOSEDSETTLDATE',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FinalAgreedSettlement: {
        table: 'ADA',
        column: 'FinalAgreedSettlement',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FinalSettlementDate: {
        table: 'ADA',
        column: 'FinalSettlementDate',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPmt9: {
        table: 'FeeStructure',
        column: 'ClientMoPmt9',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPaid_10: {
        table: 'FeeStructure',
        column: 'ClientMoPaid_10',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPaid_11: {
        table: 'FeeStructure',
        column: 'ClientMoPaid_11',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      Settled_20: {
        table: 'Tracking',
        column: 'Settled_20',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      Step16Completed: {
        table: 'Tracking',
        column: 'Step16Completed',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      AttorneyStatusNotes: {
        table: 'AttorneyUpdate',
        column: 'AttorneyStatusNotes',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      Modifydate: {
        table: 'AttorneyUpdate',
        column: 'Modifydate',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      Modifyuser: {
        table: 'AttorneyUpdate',
        column: 'Modifyuser',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPmtType: {
        table: 'FeeStructure',
        column: 'ClientMoPmtType',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      SettlementDue: {
        table: 'FeeStructure',
        column: 'SettlementDue',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      SettlementDueDate: {
        table: 'FeeStructure',
        column: 'SettlementDueDate',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      GrossRevTotal: {
        table: 'FeeStructure',
        column: 'Rule68Amt',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      AffiliateScheduled2: {
        table: 'FeeStructure',
        column: 'AffiliateScheduled2',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      LastAmtPaid: {
        table: 'FeeStructure',
        column: 'LastAmtPaid',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      LastPmtMade: {
        table: 'FeeStructure',
        column: 'LastPmtMade',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientNetTotal: {
        table: 'FeeStructure',
        column: 'ClientNetTotal',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      NetRev4: {
        table: 'FeeStructure',
        column: 'NetRev4',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      Verified1: {
        table: 'FeeStructure',
        column: 'Verified1',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostPdAmt_12: {
        table: 'FeeStructure',
        column: 'ClientCostPdAmt_12',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      NetRevTotal: {
        table: 'FeeStructure',
        column: 'NetRevTotal',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      Verified2: {
        table: 'FeeStructure',
        column: 'Verified2',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      SettlementOfferDate1: {
        table: 'CaseInfo',
        column: 'SettlementOfferDate1',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      AdvancedEFTForm: {
        table: 'FeeStructure',
        column: 'AdvancedEFTForm',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostDisc1: {
        table: 'FeeStructure',
        column: 'ClientCostDisc1',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostDisc2: {
        table: 'FeeStructure',
        column: 'ClientCostDisc2',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostDisc3: {
        table: 'FeeStructure',
        column: 'ClientCostDisc3',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostDisc4: {
        table: 'FeeStructure',
        column: 'ClientCostDisc4',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostDisc5: {
        table: 'FeeStructure',
        column: 'ClientCostDisc5',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostDisc6: {
        table: 'FeeStructure',
        column: 'ClientCostDisc6',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostDisc7: {
        table: 'FeeStructure',
        column: 'ClientCostDisc7',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostDisc8: {
        table: 'FeeStructure',
        column: 'ClientCostDisc8',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostDisc9: {
        table: 'FeeStructure',
        column: 'ClientCostDisc9',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostDisc10: {
        table: 'FeeStructure',
        column: 'ClientCostDisc10',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostDisc11: {
        table: 'FeeStructure',
        column: 'ClientCostDisc11',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostDisc12: {
        table: 'FeeStructure',
        column: 'ClientCostDisc12',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostAmt1: {
        table: 'FeeStructure',
        column: 'ClientCostAmt1',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostAmt2: {
        table: 'FeeStructure',
        column: 'ClientCostAmt2',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostAmt3: {
        table: 'FeeStructure',
        column: 'ClientCostAmt3',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostAmt4: {
        table: 'FeeStructure',
        column: 'ClientCostAmt4',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostAmt5: {
        table: 'FeeStructure',
        column: 'ClientCostAmt5',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostAmt6: {
        table: 'FeeStructure',
        column: 'ClientCostAmt6',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostAmt7: {
        table: 'FeeStructure',
        column: 'ClientCostAmt7',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostAmt8: {
        table: 'FeeStructure',
        column: 'ClientCostAmt8',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostAmt9: {
        table: 'FeeStructure',
        column: 'ClientCostAmt9',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostAmt10: {
        table: 'FeeStructure',
        column: 'ClientCostAmt10',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostAmt11: {
        table: 'FeeStructure',
        column: 'ClientCostAmt11',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostAmt12: {
        table: 'FeeStructure',
        column: 'ClientCostAmt12',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostAmtTotal: {
        table: 'FeeStructure',
        column: 'ClientCostAmtTotal',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostDue1: {
        table: 'FeeStructure',
        column: 'ClientCostDue1',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostDue2: {
        table: 'FeeStructure',
        column: 'ClientCostDue2',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostDue3: {
        table: 'FeeStructure',
        column: 'ClientCostDue3',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostDue4: {
        table: 'FeeStructure',
        column: 'ClientCostDue4',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostDue5: {
        table: 'FeeStructure',
        column: 'ClientCostDue5',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostDue6: {
        table: 'FeeStructure',
        column: 'ClientCostDue6',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostDue7: {
        table: 'FeeStructure',
        column: 'ClientCostDue7',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostDue8: {
        table: 'FeeStructure',
        column: 'ClientCostDue8',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostDue9: {
        table: 'FeeStructure',
        column: 'ClientCostDue9',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostDue10: {
        table: 'FeeStructure',
        column: 'ClientCostDue10',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostDue11: {
        table: 'FeeStructure',
        column: 'ClientCostDue11',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostDue12: {
        table: 'FeeStructure',
        column: 'ClientCostDue12',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostPdAmt1: {
        table: 'FeeStructure',
        column: 'ClientCostPdAmt1',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostPdAmt2: {
        table: 'FeeStructure',
        column: 'ClientCostPdAmt2',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostPdAmt3: {
        table: 'FeeStructure',
        column: 'ClientCostPdAmt3',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostPdAmt4: {
        table: 'FeeStructure',
        column: 'ClientCostPdAmt4',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostPdAmt5: {
        table: 'FeeStructure',
        column: 'ClientCostPdAmt5',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostPdAmt6: {
        table: 'FeeStructure',
        column: 'ClientCostPdAmt6',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostPdAmt7: {
        table: 'FeeStructure',
        column: 'ClientCostPdAmt7',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostPdAmt8: {
        table: 'FeeStructure',
        column: 'ClientCostPdAmt8',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostPdAmt9: {
        table: 'FeeStructure',
        column: 'ClientCostPdAmt9',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostPdAmt10: {
        table: 'FeeStructure',
        column: 'ClientCostPdAmt10',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostPdAmt11: {
        table: 'FeeStructure',
        column: 'ClientCostPdAmt11',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostPdAmt12: {
        table: 'FeeStructure',
        column: 'ClientCostPdAmt12',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostPaid1: {
        table: 'FeeStructure',
        column: 'ClientCostPaid1',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostPaid2: {
        table: 'FeeStructure',
        column: 'ClientCostPaid2',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostPaid3: {
        table: 'FeeStructure',
        column: 'ClientCostPaid3',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostPaid4: {
        table: 'FeeStructure',
        column: 'ClientCostPaid4',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostPaid5: {
        table: 'FeeStructure',
        column: 'ClientCostPaid5',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostPaid6: {
        table: 'FeeStructure',
        column: 'ClientCostPaid6',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostPaid7: {
        table: 'FeeStructure',
        column: 'ClientCostPaid7',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostPaid8: {
        table: 'FeeStructure',
        column: 'ClientCostPaid8',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostPaid9: {
        table: 'FeeStructure',
        column: 'ClientCostPaid9',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostPaid10: {
        table: 'FeeStructure',
        column: 'ClientCostAmt1',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostPaid11: {
        table: 'FeeStructure',
        column: 'ClientCostAmt1',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostPaid12: {
        table: 'FeeStructure',
        column: 'ClientCostAmt1',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientCostPdAmtTotal: {
        table: 'FeeStructure',
        column: 'ClientCostPdAmtTotal',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPmt1: {
        table: 'FeeStructure',
        column: 'ClientMoPmt1',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPmt2: {
        table: 'FeeStructure',
        column: 'ClientMoPmt2',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPmt3: {
        table: 'FeeStructure',
        column: 'ClientMoPmt3',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPmt4: {
        table: 'FeeStructure',
        column: 'ClientMoPmt4',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPmt5: {
        table: 'FeeStructure',
        column: 'ClientMoPmt5',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPmt6: {
        table: 'FeeStructure',
        column: 'ClientMoPmt6',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPmt7: {
        table: 'FeeStructure',
        column: 'ClientMoPmt7',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPmt8: {
        table: 'FeeStructure',
        column: 'ClientMoPmt8',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPmt_10: {
        table: 'FeeStructure',
        column: 'ClientMoPmt_10',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPmt_11: {
        table: 'FeeStructure',
        column: 'ClientMoPmt_11',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPmt_12: {
        table: 'FeeStructure',
        column: 'ClientMoPmt_12',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPmt_13: {
        table: 'FeeStructure',
        column: 'ClientMoPmt_13',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPmt_14: {
        table: 'FeeStructure',
        column: 'ClientMoPmt_14',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPmt_15: {
        table: 'FeeStructure',
        column: 'ClientMoPmt_15',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPmt_16: {
        table: 'FeeStructure',
        column: 'ClientMoPmt_16',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPmtTotal: {
        table: 'FeeStructure',
        column: 'ClientMoPmtTotal',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoDue1: {
        table: 'FeeStructure',
        column: 'ClientMoDue1',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoDue2: {
        table: 'FeeStructure',
        column: 'ClientMoDue2',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoDue3: {
        table: 'FeeStructure',
        column: 'ClientMoDue3',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoDue4: {
        table: 'FeeStructure',
        column: 'ClientMoDue4',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoDue5: {
        table: 'FeeStructure',
        column: 'ClientMoDue5',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoDue6: {
        table: 'FeeStructure',
        column: 'ClientMoDue6',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoDue7: {
        table: 'FeeStructure',
        column: 'ClientMoDue7',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoDue8: {
        table: 'FeeStructure',
        column: 'ClientMoDue8',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoDue9: {
        table: 'FeeStructure',
        column: 'ClientMoDue9',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoDue_10: {
        table: 'FeeStructure',
        column: 'ClientMoDue_10',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoDue_11: {
        table: 'FeeStructure',
        column: 'ClientMoDue_11',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoDue_12: {
        table: 'FeeStructure',
        column: 'ClientMoDue_12',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoDue_13: {
        table: 'FeeStructure',
        column: 'ClientMoDue_13',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoDue_14: {
        table: 'FeeStructure',
        column: 'ClientMoDue_14',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoDue_15: {
        table: 'FeeStructure',
        column: 'ClientMoDue_15',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoDue_16: {
        table: 'FeeStructure',
        column: 'ClientMoDue_16',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPayment1: {
        table: 'FeeStructure',
        column: 'ClientMoPayment1',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPayment2: {
        table: 'FeeStructure',
        column: 'ClientMoPayment2',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPayment3: {
        table: 'FeeStructure',
        column: 'ClientMoPayment3',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPayment4: {
        table: 'FeeStructure',
        column: 'ClientMoPayment4',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPayment5: {
        table: 'FeeStructure',
        column: 'ClientMoPayment5',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPayment6: {
        table: 'FeeStructure',
        column: 'ClientMoPayment6',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPayment7: {
        table: 'FeeStructure',
        column: 'ClientMoPayment7',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPayment8: {
        table: 'FeeStructure',
        column: 'ClientMoPayment8',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPayment9: {
        table: 'FeeStructure',
        column: 'ClientMoPayment9',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPayment_10: {
        table: 'FeeStructure',
        column: 'ClientMoPayment_10',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPayment_11: {
        table: 'FeeStructure',
        column: 'ClientMoPayment_11',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPayment_12: {
        table: 'FeeStructure',
        column: 'ClientMoPayment_12',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPayment_13: {
        table: 'FeeStructure',
        column: 'ClientMoPayment_13',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPayment_14: {
        table: 'FeeStructure',
        column: 'ClientMoPayment_14',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPayment_15: {
        table: 'FeeStructure',
        column: 'ClientMoPayment_15',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPayment_16: {
        table: 'FeeStructure',
        column: 'ClientMoPayment_16',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPaidTotal: {
        table: 'FeeStructure',
        column: 'ClientMoPaidTotal',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPaid1: {
        table: 'FeeStructure',
        column: 'ClientMoPaid1',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPaid2: {
        table: 'FeeStructure',
        column: 'ClientMoPaid2',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPaid3: {
        table: 'FeeStructure',
        column: 'ClientMoPaid3',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPaid4: {
        table: 'FeeStructure',
        column: 'ClientMoPaid4',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPaid5: {
        table: 'FeeStructure',
        column: 'ClientMoPaid5',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPaid6: {
        table: 'FeeStructure',
        column: 'ClientMoPaid6',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPaid7: {
        table: 'FeeStructure',
        column: 'ClientMoPaid7',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPaid8: {
        table: 'FeeStructure',
        column: 'ClientMoPaid8',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPaid9: {
        table: 'FeeStructure',
        column: 'ClientMoPaid9',
        identifier: opportunityId,
        key: 'OpportunityId',
      },

      ClientMoPaid_12: {
        table: 'FeeStructure',
        column: 'ClientMoPaid12',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPaid_13: {
        table: 'FeeStructure',
        column: 'ClientMoPaid_13',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPaid_14: {
        table: 'FeeStructure',
        column: 'ClientMoPaid_14',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPaid_15: {
        table: 'FeeStructure',
        column: 'ClientMoPaid_15',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      ClientMoPaid_16: {
        table: 'FeeStructure',
        column: 'ClientMoPaid_16',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmClient1: {
        table: 'FeeStructure',
        column: 'FirmClient1',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmClient2: {
        table: 'FeeStructure',
        column: 'FirmClient2',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmClient3: {
        table: 'FeeStructure',
        column: 'FirmClient3',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmClient4: {
        table: 'FeeStructure',
        column: 'FirmClient4',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmClient5: {
        table: 'FeeStructure',
        column: 'FirmClient5',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmClient6: {
        table: 'FeeStructure',
        column: 'FirmClient6',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmClient7: {
        table: 'FeeStructure',
        column: 'FirmClient7',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmClient8: {
        table: 'FeeStructure',
        column: 'FirmClient8',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmClient9: {
        table: 'FeeStructure',
        column: 'FirmClient9',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmClient_10: {
        table: 'FeeStructure',
        column: 'FirmClient_10',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmClient_11: {
        table: 'FeeStructure',
        column: 'FirmClient_11',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmClient_12: {
        table: 'FeeStructure',
        column: 'FirmClient_12',
        identifier: opportunityId,
        key: 'OpportunityId',
      },

      FirmClient_13: {
        table: 'FeeStructure',
        column: 'FirmClient_13',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmClient_14: {
        table: 'FeeStructure',
        column: 'FirmClient_14',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmClient_15: {
        table: 'FeeStructure',
        column: 'FirmClient_15',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmClient_16: {
        table: 'FeeStructure',
        column: 'FirmClient_16',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmClientTotal: {
        table: 'FeeStructure',
        column: 'FirmClientTotal',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmPaid1: {
        table: 'FeeStructure',
        column: 'FirmPaid1',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmPaid2: {
        table: 'FeeStructure',
        column: 'FirmPaid2',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmPaid3: {
        table: 'FeeStructure',
        column: 'FirmPaid3',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmPaid4: {
        table: 'FeeStructure',
        column: 'FirmPaid4',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmPaid5: {
        table: 'FeeStructure',
        column: 'FirmPaid5',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmPaid6: {
        table: 'FeeStructure',
        column: 'FirmPaid6',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmPaid7: {
        table: 'FeeStructure',
        column: 'FirmPaid7',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmPaid8: {
        table: 'FeeStructure',
        column: 'FirmPaid8',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmPaid9: {
        table: 'FeeStructure',
        column: 'FirmPaid9',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmPaid_10: {
        table: 'FeeStructure',
        column: 'FirmPaid_10',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmPaid_11: {
        table: 'FeeStructure',
        column: 'FirmPaid_11',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmPaid_12: {
        table: 'FeeStructure',
        column: 'FirmPaid_12',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmPaid_13: {
        table: 'FeeStructure',
        column: 'FirmPaid_13',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmPaid_14: {
        table: 'FeeStructure',
        column: 'FirmPaid_14',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmPaid_15: {
        table: 'FeeStructure',
        column: 'FirmPaid_15',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmPaid_16: {
        table: 'FeeStructure',
        column: 'FirmPaid_16',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      FirmPaidTotal: {
        table: 'FeeStructure',
        column: 'FirmPaidTotal',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      NSF1: {
        table: 'FeeStructure',
        column: 'NSF1',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      NSF2: {
        table: 'FeeStructure',
        column: 'NSF2',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      NSF3: {
        table: 'FeeStructure',
        column: 'NSF3',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      NSF4: {
        table: 'FeeStructure',
        column: 'NSF4',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      NSF5: {
        table: 'FeeStructure',
        column: 'NSF5',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      NSF6: {
        table: 'FeeStructure',
        column: 'NSF6',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      NSF7: {
        table: 'FeeStructure',
        column: 'NSF7',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      NSF8: {
        table: 'FeeStructure',
        column: 'NSF8',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      NSF9: {
        table: 'FeeStructure',
        column: 'NSF9',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      NSF10: {
        table: 'FeeStructure',
        column: 'NSF10',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      NSF11: {
        table: 'FeeStructure',
        column: 'NSF11',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      NSF12: {
        table: 'FeeStructure',
        column: 'NSF12',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      NSF13: {
        table: 'FeeStructure',
        column: 'NSF13',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      NSF14: {
        table: 'FeeStructure',
        column: 'NSF14',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      NSF15: {
        table: 'FeeStructure',
        column: 'NSF15',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      NSF16: {
        table: 'FeeStructure',
        column: 'NSF16',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      TrustPayor1: {
        table: 'FeeStructure',
        column: 'TrustPayor1',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      TrustPayor2: {
        table: 'FeeStructure',
        column: 'TrustPayor2',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      TrustPayor3: {
        table: 'FeeStructure',
        column: 'TrustPayor3',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      TrustPayor4: {
        table: 'FeeStructure',
        column: 'TrustPayor4',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      TrustPayor5: {
        table: 'FeeStructure',
        column: 'TrustPayor5',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      TrustPayor6: {
        table: 'FeeStructure',
        column: 'TrustPayor6',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      TrustAmtInPurp1: {
        table: 'FeeStructure',
        column: 'TrustAmtInPurp1',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      TrustAmtInPurp2: {
        table: 'FeeStructure',
        column: 'TrustAmtInPurp2',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      TrustAmtInPurp3: {
        table: 'FeeStructure',
        column: 'TrustAmtInPurp3',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      TrustAmtInPurp4: {
        table: 'FeeStructure',
        column: 'TrustAmtInPurp4',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      TrustAmtInPurp5: {
        table: 'FeeStructure',
        column: 'TrustAmtInPurp5',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      TrustAmtInPurp6: {
        table: 'FeeStructure',
        column: 'TrustAmtInPurp6',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      TrustAmtIn1: {
        table: 'FeeStructure',
        column: 'TrustAmtIn1',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      TrustAmtIn2: {
        table: 'FeeStructure',
        column: 'TrustAmtIn2',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      TrustAmtIn3: {
        table: 'FeeStructure',
        column: 'TrustAmtIn3',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      TrustAmtIn4: {
        table: 'FeeStructure',
        column: 'TrustAmtIn4',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      TrustAmtIn5: {
        table: 'FeeStructure',
        column: 'TrustAmtIn5',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      TrustAmtIn6: {
        table: 'FeeStructure',
        column: 'TrustAmtIn6',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      TrustBalance: {
        table: 'FeeStructure',
        column: 'TrustBalance',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      TrustInDate1: {
        table: 'FeeStructure',
        column: 'TrustInDate1',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      TrustInDate2: {
        table: 'FeeStructure',
        column: 'TrustInDate2',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      TrustInDate3: {
        table: 'FeeStructure',
        column: 'TrustInDate3',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      TrustInDate4: {
        table: 'FeeStructure',
        column: 'TrustInDate4',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      TrustInDate5: {
        table: 'FeeStructure',
        column: 'TrustInDate5',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
      TrustInDate6: {
        table: 'FeeStructure',
        column: 'TrustInDate6',
        identifier: opportunityId,
        key: 'OpportunityId',
      },
















    }
  }

  initForm(fb: FormBuilder): FormGroup {

    const form = fb.group({
      total2: fb.control(''),
      NextPmtAmount: fb.control(''),
      Settled_20: fb.control(''),
      Party2Name: fb.control(''),
      Party4email: fb.control(''),
      ClientID: fb.control(''),
      TCPA_State: fb.control(''),
      Advisor2: fb.control(''),
      Defendant1Long: fb.control(''),
      Party4Name: fb.control(''),
      Party4Title: fb.control(''),
      Party4phone: fb.control(''),
      Party1Co: fb.control(''),
      Party1Name: fb.control(''),
      Party1phone: fb.control(''),
      Party1direct: fb.control(''),
      Party1email: fb.control(''),
      PlaintiffPhoneAcquire: fb.control(''),
      CRED1PROOF: fb.control(''),
      Party2Co: fb.control(''),
      Party2phone: fb.control(''),
      Party2direct: fb.control(''),
      Party2email: fb.control(''),
      PMTDeclaration1: fb.control(''),
      CRED2PROOF: fb.control(''),
      RecvdSettlOPC: fb.control(''),
      misc1disc: fb.control(''),
      InitialContactOPC: fb.control(''),
      LegalAssistant2: fb.control(''),
      misc2disc: fb.control(''),
      SARDate: fb.control(''),
      PaymentReceived: fb.control(''),
      drafted68: fb.control(''),
      drafted68box: fb.control(''),
      Rule68Amt: fb.control(''),
      Rule68Offersent: fb.control(''),
      Rule68DefRespDue: fb.control(''),
      InitialDemand: fb.control(''),
      InitialDemandDate: fb.control(''),
      InitialOffer: fb.control(''),
      InitialOfferDate: fb.control(''),
      CounterSettl: fb.control(''),
      CounterSettlDate: fb.control(''),
      ProposedSettl: fb.control(''),
      PROPOSEDSETTLDATE: fb.control(''),
      FinalAgreedSettlement: fb.control(''),
      FinalSettlementDate: fb.control(''),
      Rule68: fb.control(''),
      Rule668Date: fb.control(''),
      Rule68RestDue: fb.control(''),
      RemediationDate: fb.control(''),
      Step16Completed: fb.control(''),
      AttorneyStatusNotes: fb.control(''),
      Modifydate: fb.control(''),
      Modifyuser: fb.control(''),
      ClientMoPmtType: fb.control(''),
      SettlementDue: fb.control(''),
      SettlementDueDate: fb.control(''),
      GrossRevTotal: fb.control(''),
      AffiliateScheduled2: fb.control(''),
      LastAmtPaid: fb.control(''),
      LastPmtMade: fb.control(''),
      NextPmtAmt: fb.control(''),
      NextPmtDue: fb.control(''),
      ClientNetTotal: fb.control(''),
      NetRev4: fb.control(''),
      Verified1: fb.control(''),
      ClientCostPdAmt_12: fb.control(''),
      NetRevTotal: fb.control(''),
      Verified2: fb.control(''),
      SettlementOfferDate1: fb.control(''),
      Summary: fb.control(''),
      AdvancedEFTForm: fb.control(''),
      ClientCostDisc1: fb.control(''),
      ClientCostDisc2: fb.control(''),
      ClientCostDisc3: fb.control(''),
      ClientCostDisc4: fb.control(''),
      ClientCostDisc5: fb.control(''),
      ClientCostDisc6: fb.control(''),
      ClientCostDisc7: fb.control(''),
      ClientCostDisc8: fb.control(''),
      ClientCostDisc9: fb.control(''),
      ClientCostDisc10: fb.control(''),
      ClientCostDisc11: fb.control(''),
      ClientCostDisc12: fb.control(''),
      ClientCostAmt1: fb.control(''),
      ClientCostAmt2: fb.control(''),
      ClientCostAmt3: fb.control(''),
      ClientCostAmt4: fb.control(''),
      ClientCostAmt5: fb.control(''),
      ClientCostAmt6: fb.control(''),
      ClientCostAmt7: fb.control(''),
      ClientCostAmt8: fb.control(''),
      ClientCostAmt9: fb.control(''),
      ClientCostAmt10: fb.control(''),
      ClientCostAmt11: fb.control(''),
      ClientCostAmt12: fb.control(''),
      ClientCostAmtTotal: fb.control(''),
      ClientCostDue1: fb.control(''),
      ClientCostDue2: fb.control(''),
      ClientCostDue3: fb.control(''),
      ClientCostDue4: fb.control(''),
      ClientCostDue5: fb.control(''),
      ClientCostDue6: fb.control(''),
      ClientCostDue7: fb.control(''),
      ClientCostDue8: fb.control(''),
      ClientCostDue9: fb.control(''),
      ClientCostDue10: fb.control(''),
      ClientCostDue11: fb.control(''),
      ClientCostDue12: fb.control(''),
      ClientCostPdAmt1: fb.control(''),
      ClientCostPdAmt2: fb.control(''),
      ClientCostPdAmt3: fb.control(''),
      ClientCostPdAmt4: fb.control(''),
      ClientCostPdAmt5: fb.control(''),
      ClientCostPdAmt6: fb.control(''),
      ClientCostPdAmt7: fb.control(''),
      ClientCostPdAmt8: fb.control(''),
      ClientCostPdAmt9: fb.control(''),
      ClientCostPdAmt10: fb.control(''),
      ClientCostPdAmt11: fb.control(''),
      ClientCostPdAmt12: fb.control(''),
      ClientCostPaidTotal: fb.control(''),
      ClientCostPaid1: fb.control(''),
      ClientCostPaid2: fb.control(''),
      ClientCostPaid3: fb.control(''),
      ClientCostPaid4: fb.control(''),
      ClientCostPaid5: fb.control(''),
      ClientCostPaid6: fb.control(''),
      ClientCostPaid7: fb.control(''),
      ClientCostPaid8: fb.control(''),
      ClientCostPaid9: fb.control(''),
      ClientCostPaid10: fb.control(''),
      ClientCostPaid11: fb.control(''),
      ClientCostPaid12: fb.control(''),
      ClientCostPdAmtTotal: fb.control(''),
      ClientMoPmt1: fb.control(''),
      ClientMoPmt2: fb.control(''),
      ClientMoPmt3: fb.control(''),
      ClientMoPmt4: fb.control(''),
      ClientMoPmt5: fb.control(''),
      ClientMoPmt6: fb.control(''),
      ClientMoPmt7: fb.control(''),
      ClientMoPmt8: fb.control(''),
      ClientMoPmt9: fb.control(''),
      ClientMoPmt_10: fb.control(''),
      ClientMoPmt_11: fb.control(''),
      ClientMoPmt_12: fb.control(''),
      ClientMoPmt_13: fb.control(''),
      ClientMoPmt_14: fb.control(''),
      ClientMoPmt_15: fb.control(''),
      ClientMoPmt_16: fb.control(''),
      ClientMoPmtTotal: fb.control(''),
      ClientMoDue1: fb.control(''),
      ClientMoDue2: fb.control(''),
      ClientMoDue3: fb.control(''),
      ClientMoDue4: fb.control(''),
      ClientMoDue5: fb.control(''),
      ClientMoDue6: fb.control(''),
      ClientMoDue7: fb.control(''),
      ClientMoDue8: fb.control(''),
      ClientMoDue9: fb.control(''),
      ClientMoDue_10: fb.control(''),
      ClientMoDue_11: fb.control(''),
      ClientMoDue_12: fb.control(''),
      ClientMoDue_13: fb.control(''),
      ClientMoDue_14: fb.control(''),
      ClientMoDue_15: fb.control(''),
      ClientMoDue_16: fb.control(''),
      ClientMoPayment1: fb.control(''),
      ClientMoPayment2: fb.control(''),
      ClientMoPayment3: fb.control(''),
      ClientMoPayment4: fb.control(''),
      ClientMoPayment5: fb.control(''),
      ClientMoPayment6: fb.control(''),
      ClientMoPayment7: fb.control(''),
      ClientMoPayment8: fb.control(''),
      ClientMoPayment9: fb.control(''),
      ClientMoPayment_10: fb.control(''),
      ClientMoPayment_11: fb.control(''),
      ClientMoPayment_12: fb.control(''),
      ClientMoPayment_13: fb.control(''),
      ClientMoPayment_14: fb.control(''),
      ClientMoPayment_15: fb.control(''),
      ClientMoPayment_16: fb.control(''),
      ClientMoPaidTotal: fb.control(''),
      ClientMoPaid1: fb.control(''),
      ClientMoPaid2: fb.control(''),
      ClientMoPaid3: fb.control(''),
      ClientMoPaid4: fb.control(''),
      ClientMoPaid5: fb.control(''),
      ClientMoPaid6: fb.control(''),
      ClientMoPaid7: fb.control(''),
      ClientMoPaid8: fb.control(''),
      ClientMoPaid9: fb.control(''),
      ClientMoPaid_10: fb.control(''),
      ClientMoPaid_11: fb.control(''),
      ClientMoPaid_12: fb.control(''),
      ClientMoPaid_13: fb.control(''),
      ClientMoPaid_14: fb.control(''),
      ClientMoPaid_15: fb.control(''),
      ClientMoPaid_16: fb.control(''),
      FirmClient1: fb.control(''),
      FirmClient2: fb.control(''),
      FirmClient3: fb.control(''),
      FirmClient4: fb.control(''),
      FirmClient5: fb.control(''),
      FirmClient6: fb.control(''),
      FirmClient7: fb.control(''),
      FirmClient8: fb.control(''),
      FirmClient9: fb.control(''),
      FirmClient_10: fb.control(''),
      FirmClient_11: fb.control(''),
      FirmClient_12: fb.control(''),
      FirmClient_13: fb.control(''),
      FirmClient_14: fb.control(''),
      FirmClient_15: fb.control(''),
      FirmClient_16: fb.control(''),
      FirmClientTotal: fb.control(''),
      FirmPaid1: fb.control(''),
      FirmPaid2: fb.control(''),
      FirmPaid3: fb.control(''),
      FirmPaid4: fb.control(''),
      FirmPaid5: fb.control(''),
      FirmPaid6: fb.control(''),
      FirmPaid7: fb.control(''),
      FirmPaid8: fb.control(''),
      FirmPaid9: fb.control(''),
      FirmPaid_10: fb.control(''),
      FirmPaid_11: fb.control(''),
      FirmPaid_12: fb.control(''),
      FirmPaid_13: fb.control(''),
      FirmPaid_14: fb.control(''),
      FirmPaid_15: fb.control(''),
      FirmPaid_16: fb.control(''),
      FirmPaidTotal: fb.control(''),
      NSF2: fb.control(''),
      NSF3: fb.control(''),
      NSF4: fb.control(''),
      NSF5: fb.control(''),
      NSF6: fb.control(''),
      NSF7: fb.control(''),
      NSF8: fb.control(''),
      NSF9: fb.control(''),
      NSF10: fb.control(''),
      NSF11: fb.control(''),
      NSF12: fb.control(''),
      NSF13: fb.control(''),
      NSF14: fb.control(''),
      NSF15: fb.control(''),
      NSF16: fb.control(''),
      NSF1: fb.control(''),
      TrustPayor1: fb.control(''),
      TrustPayor2: fb.control(''),
      TrustPayor3: fb.control(''),
      TrustPayor4: fb.control(''),
      TrustPayor5: fb.control(''),
      TrustPayor6: fb.control(''),
      TrustAmtInPurp1: fb.control(''),
      TrustAmtInPurp2: fb.control(''),
      TrustAmtInPurp3: fb.control(''),
      TrustAmtInPurp4: fb.control(''),
      TrustAmtInPurp5: fb.control(''),
      TrustAmtInPurp6: fb.control(''),
      TrustAmtIn1: fb.control(''),
      TrustAmtIn2: fb.control(''),
      TrustAmtIn3: fb.control(''),
      TrustAmtIn4: fb.control(''),
      TrustAmtIn5: fb.control(''),
      TrustAmtIn6: fb.control(''),
      TrustBalance: fb.control(''),
      TrustInDate1: fb.control(''),
      TrustInDate2: fb.control(''),
      TrustInDate3: fb.control(''),
      TrustInDate4: fb.control(''),
      TrustInDate5: fb.control(''),
      TrustInDate6: fb.control(''),



    }, { updateOn: 'blur' });
    return form;
  }

  setFormValues(form: FormGroup, data: any, service: OpportunityService) {
    form.setValue({
      total2: getNullableDataValue(data.total2, ''),
      NextPmtAmount: getNullableDataValue(data.NextPmtAmount, ''),
      Settled_20: getNullableDateValue(data.Settled_20, ''),
      Party2Name: getNullableDataValue(data.Party2Name, ''),
      Party4email: getNullableDataValue(data.Party4email, ''),
      ClientCostPdAmtTotal: getNullableDataValue(data.ClientCostPdAmtTotal, ''),
      ClientID: getNullableDataValue(data.ClientID, ''),
      TCPA_State: getNullableDataValue(data.TCPA_State, ''),
      Advisor2: getNullableDataValue(data.Advisor2, ''),
      Defendant1Long: getNullableDataValue(data.Defendant1Long, ''),
      Party4Name: getNullableDataValue(data.Party4Name, ''),
      Party4Title: getNullableDataValue(data.Party4Title, ''),
      Party4phone: getNullableDataValue(data.Party4phone, ''),
      Party1Co: getNullableDataValue(data.Party1Co, ''),
      Party1Name: getNullableDataValue(data.Party1Name, ''),
      Party1phone: getNullableDataValue(data.Party1phone, ''),
      Party1direct: getNullableDataValue(data.Party1direct, ''),
      Party1email: getNullableDataValue(data.Party1email, ''),
      PlaintiffPhoneAcquire: getNullableDateValue(data.PlaintiffPhoneAcquire, ''),
      CRED1PROOF: getNullableDateValue(data.CRED1PROOF, ''),
      Party2Co: getNullableDataValue(data.Party2Co, ''),
      Party2phone: getNullableDataValue(data.Party2phone, ''),
      Party2direct: getNullableDataValue(data.Party2direct, ''),
      Party2email: getNullableDataValue(data.Party2email, ''),
      PMTDeclaration1: getNullableDateValue(data.PMTDeclaration1, ''),
      CRED2PROOF: getNullableDateValue(data.CRED2PROOF, ''),
      RecvdSettlOPC: getNullableDateValue(data.RecvdSettlOPC, ''),
      misc1disc: getNullableDataValue(data.misc1disc, ''),
      InitialContactOPC: getNullableDateValue(data.InitialContactOPC, ''),
      LegalAssistant2: getNullableDataValue(data.LegalAssistant2, ''),
      misc2disc: getNullableDataValue(data.misc2disc, ''),
      SARDate: getNullableDateValue(data.SARDate, ''),
      PaymentReceived: getNullableDateValue(data.PaymentReceived, ''),
      drafted68: getNullableDateValue(data.drafted68, ''),
      drafted68box: getNullableDataValue(data.drafted68box, ''),
      Rule68Amt: getNullableDataValue(data.Rule68Amt, ''),
      Rule68Offersent: getNullableDateValue(data.Rule68Offersent, ''),
      Rule68DefRespDue: getNullableDateValue(data.Rule68DefRespDue, ''),
      InitialDemand: getNullableDataValue(data.InitialDemand, ''),
      InitialDemandDate: getNullableDateValue(data.InitialDemandDate, ''),
      InitialOffer: getNullableDataValue(data.InitialOffer, ''),
      InitialOfferDate: getNullableDateValue(data.InitialOfferDate, ''),
      CounterSettl: getNullableDataValue(data.CounterSettl, ''),
      CounterSettlDate: getNullableDateValue(data.CounterSettlDate, ''),
      ProposedSettl: getNullableDataValue(data.ProposedSettl, ''),
      PROPOSEDSETTLDATE: getNullableDateValue(data.PROPOSEDSETTLDATE, ''),
      FinalAgreedSettlement: getNullableDataValue(data.FinalAgreedSettlement, ''),
      FinalSettlementDate: getNullableDateValue(data.FinalSettlementDate, ''),
      Rule68: getNullableDataValue(data.Rule68, ''),
      Rule668Date: getNullableDateValue(data.Rule668Date, ''),
      Rule68RestDue: getNullableDataValue(data.Rule68RestDue, ''),
      RemediationDate: getNullableDateValue(data.RemediationDate, ''),
      Step16Completed: getNullableDateValue(data.Step16Completed, ''),
      AttorneyStatusNotes: getNullableDataValue(data.AttorneyStatusNotes, ''),
      Modifydate: getNullableDateValue(data.Modifydate, ''),
      Modifyuser: getNullableDataValue(data.Modifyuser, ''),
      ClientMoPmtType: getNullableDateValue(data.ClientMoPmtType, ''),
      SettlementDue: getNullableDataValue(data.SettlementDue, ''),
      SettlementDueDate: getNullableDateValue(data.SettlementDueDate, ''),
      GrossRevTotal: getNullableDataValue(data.GrossRevTotal, ''),
      AffiliateScheduled2: getNullableDateValue(data.AffiliateScheduled2, ''),
      LastAmtPaid: getNullableDataValue(data.LastAmtPaid, ''),
      LastPmtMade: getNullableDateValue(data.LastPmtMade, ''),
      NextPmtAmt: getNullableDateValue(data.NextPmtAmt, ''),
      NextPmtDue: getNullableDateValue(data.NextPmtDue, ''),
      ClientNetTotal: getNullableDataValue(data.ClientNetTotal, ''),
      NetRev4: getNullableDataValue(data.NetRev4, ''),
      Verified1: getNullableDateValue(data.Verified1, ''),
      NetRevTotal: getNullableDataValue(data.NetRevTotal, ''),
      Verified2: getNullableDateValue(data.Verified2, ''),
      ClientCostPdAmt_12: getNullableDataValue(data.ClientCostPdAmt_12, ''),
      SettlementOfferDate1: getNullableDateValue(data.SettlementOfferDate1, ''),
      Summary: getNullableDataValue(data.Summary, ''),
      AdvancedEFTForm: getNullableDataValue(data.AdvancedEFTForm, ''),
      ClientCostDisc1: getNullableDataValue(data.ClientCostDisc1, ''),
      ClientCostDisc2: getNullableDataValue(data.ClientCostDisc2, ''),
      ClientCostDisc3: getNullableDataValue(data.ClientCostDisc3, ''),
      ClientCostDisc4: getNullableDataValue(data.ClientCostDisc4, ''),
      ClientCostDisc5: getNullableDataValue(data.ClientCostDisc5, ''),
      ClientCostDisc6: getNullableDataValue(data.ClientCostDisc6, ''),
      ClientCostDisc7: getNullableDataValue(data.ClientCostDisc7, ''),
      ClientCostDisc8: getNullableDataValue(data.ClientCostDisc8, ''),
      ClientCostDisc9: getNullableDataValue(data.ClientCostDisc9, ''),
      ClientCostDisc10: getNullableDataValue(data.ClientCostDisc10, ''),
      ClientCostDisc11: getNullableDataValue(data.ClientCostDisc11, ''),
      ClientCostDisc12: getNullableDataValue(data.ClientCostDisc12, ''),
      ClientCostAmt1: getNullableDataValue(data.ClientCostAmt1, ''),
      ClientCostAmt2: getNullableDataValue(data.ClientCostAmt2, ''),
      ClientCostAmt3: getNullableDataValue(data.ClientCostAmt3, ''),
      ClientCostAmt4: getNullableDataValue(data.ClientCostAmt4, ''),
      ClientCostAmt5: getNullableDataValue(data.ClientCostAmt5, ''),
      ClientCostAmt6: getNullableDataValue(data.ClientCostAmt6, ''),
      ClientCostAmt7: getNullableDataValue(data.ClientCostAmt7, ''),
      ClientCostAmt8: getNullableDataValue(data.ClientCostAmt8, ''),
      ClientCostAmt9: getNullableDataValue(data.ClientCostAmt9, ''),
      ClientCostAmt10: getNullableDataValue(data.ClientCostAmt10, ''),
      ClientCostAmt11: getNullableDataValue(data.ClientCostAmt11, ''),
      ClientCostAmt12: getNullableDataValue(data.ClientCostAmt12, ''),
      ClientCostAmtTotal: getNullableDataValue(data.ClientCostAmtTotal, ''),
      ClientCostDue1: getNullableDateValue(data.ClientCostDue1, ''),
      ClientCostDue2: getNullableDateValue(data.ClientCostDue2, ''),
      ClientCostDue3: getNullableDateValue(data.ClientCostDue3, ''),
      ClientCostDue4: getNullableDateValue(data.ClientCostDue4, ''),
      ClientCostDue5: getNullableDateValue(data.ClientCostDue5, ''),
      ClientCostDue6: getNullableDateValue(data.ClientCostDue6, ''),
      ClientCostDue7: getNullableDateValue(data.ClientCostDue7, ''),
      ClientCostDue8: getNullableDateValue(data.ClientCostDue8, ''),
      ClientCostDue9: getNullableDateValue(data.ClientCostDue9, ''),
      ClientCostDue10: getNullableDateValue(data.ClientCostDue10, ''),
      ClientCostDue11: getNullableDateValue(data.ClientCostDue11, ''),
      ClientCostDue12: getNullableDateValue(data.ClientCostDue12, ''),
      ClientCostPdAmt1: getNullableDataValue(data.ClientCostPdAmt1, ''),
      ClientCostPdAmt2: getNullableDataValue(data.ClientCostPdAmt1, ''),
      ClientCostPdAmt3: getNullableDataValue(data.ClientCostPdAmt1, ''),
      ClientCostPdAmt4: getNullableDataValue(data.ClientCostPdAmt1, ''),
      ClientCostPdAmt5: getNullableDataValue(data.ClientCostPdAmt1, ''),
      ClientCostPdAmt6: getNullableDataValue(data.ClientCostPdAmt1, ''),
      ClientCostPdAmt7: getNullableDataValue(data.ClientCostPdAmt1, ''),
      ClientCostPdAmt8: getNullableDataValue(data.ClientCostPdAmt1, ''),
      ClientCostPdAmt9: getNullableDataValue(data.ClientCostPdAmt1, ''),
      ClientCostPdAmt10: getNullableDataValue(data.ClientCostPdAmt1, ''),
      ClientCostPdAmt11: getNullableDataValue(data.ClientCostPdAmt1, ''),
      ClientCostPdAmt12: getNullableDataValue(data.ClientCostPdAmt1, ''),
      ClientCostPaidTotal: getNullableDataValue(data.ClientCostPaidTotal, ''),
      ClientCostPaid1: getNullableDateValue(data.ClientCostPaid1, ''),
      ClientCostPaid2: getNullableDateValue(data.ClientCostPaid2, ''),
      ClientCostPaid3: getNullableDateValue(data.ClientCostPaid3, ''),
      ClientCostPaid4: getNullableDateValue(data.ClientCostPaid4, ''),
      ClientCostPaid5: getNullableDateValue(data.ClientCostPaid5, ''),
      ClientCostPaid6: getNullableDateValue(data.ClientCostPaid6, ''),
      ClientCostPaid7: getNullableDateValue(data.ClientCostPaid7, ''),
      ClientCostPaid8: getNullableDateValue(data.ClientCostPaid8, ''),
      ClientCostPaid9: getNullableDateValue(data.ClientCostPaid9, ''),
      ClientCostPaid10: getNullableDateValue(data.ClientCostPaid10, ''),
      ClientCostPaid11: getNullableDateValue(data.ClientCostPaid11, ''),
      ClientCostPaid12: getNullableDateValue(data.ClientCostPaid12, ''),
      ClientMoPmt1: getNullableDataValue(data.ClientMoPmt1, ''),
      ClientMoPmt2: getNullableDataValue(data.ClientMoPmt2, ''),
      ClientMoPmt3: getNullableDataValue(data.ClientMoPmt3, ''),
      ClientMoPmt4: getNullableDataValue(data.ClientMoPmt4, ''),
      ClientMoPmt5: getNullableDataValue(data.ClientMoPmt5, ''),
      ClientMoPmt6: getNullableDataValue(data.ClientMoPmt6, ''),
      ClientMoPmt7: getNullableDataValue(data.ClientMoPmt7, ''),
      ClientMoPmt8: getNullableDataValue(data.ClientMoPmt8, ''),
      ClientMoPmt9: getNullableDataValue(data.ClientMoPmt9, ''),
      ClientMoPmt_10: getNullableDataValue(data.ClientMoPmt_10, ''),
      ClientMoPmt_11: getNullableDataValue(data.ClientMoPmt_11, ''),
      ClientMoPmt_12: getNullableDataValue(data.ClientMoPmt_12, ''),
      ClientMoPmt_13: getNullableDataValue(data.ClientMoPmt_13, ''),
      ClientMoPmt_14: getNullableDataValue(data.ClientMoPmt_14, ''),
      ClientMoPmt_15: getNullableDataValue(data.ClientMoPmt_15, ''),
      ClientMoPmt_16: getNullableDataValue(data.ClientMoPmt_16, ''),
      ClientMoPmtTotal: getNullableDataValue(data.ClientMoPmtTotal, ''),
      ClientMoDue1: getNullableDateValue(data.ClientMoDue1, ''),
      ClientMoDue2: getNullableDateValue(data.ClientMoDue2, ''),
      ClientMoDue3: getNullableDateValue(data.ClientMoDue3, ''),
      ClientMoDue4: getNullableDateValue(data.ClientMoDue4, ''),
      ClientMoDue5: getNullableDateValue(data.ClientMoDue5, ''),
      ClientMoDue6: getNullableDateValue(data.ClientMoDue6, ''),
      ClientMoDue7: getNullableDateValue(data.ClientMoDue7, ''),
      ClientMoDue8: getNullableDateValue(data.ClientMoDue8, ''),
      ClientMoDue9: getNullableDateValue(data.ClientMoDue9, ''),
      ClientMoDue_10: getNullableDateValue(data.ClientMoDue_10, ''),
      ClientMoDue_11: getNullableDateValue(data.ClientMoDue_11, ''),
      ClientMoDue_12: getNullableDateValue(data.ClientMoDue_12, ''),
      ClientMoDue_13: getNullableDateValue(data.ClientMoDue_13, ''),
      ClientMoDue_14: getNullableDateValue(data.ClientMoDue_14, ''),
      ClientMoDue_15: getNullableDateValue(data.ClientMoDue_15, ''),
      ClientMoDue_16: getNullableDateValue(data.ClientMoDue_16, ''),
      ClientMoPayment1: getNullableDataValue(data.ClientMoPayment1, ''),
      ClientMoPayment2: getNullableDataValue(data.ClientMoPayment2, ''),
      ClientMoPayment3: getNullableDataValue(data.ClientMoPayment3, ''),
      ClientMoPayment4: getNullableDataValue(data.ClientMoPayment4, ''),
      ClientMoPayment5: getNullableDataValue(data.ClientMoPayment5, ''),
      ClientMoPayment6: getNullableDataValue(data.ClientMoPayment6, ''),
      ClientMoPayment7: getNullableDataValue(data.ClientMoPayment7, ''),
      ClientMoPayment8: getNullableDataValue(data.ClientMoPayment8, ''),
      ClientMoPayment9: getNullableDataValue(data.ClientMoPayment9, ''),
      ClientMoPayment_10: getNullableDataValue(data.ClientMoPayment_10, ''),
      ClientMoPayment_11: getNullableDataValue(data.ClientMoPayment_11, ''),
      ClientMoPayment_12: getNullableDataValue(data.ClientMoPayment_12, ''),
      ClientMoPayment_13: getNullableDataValue(data.ClientMoPayment_13, ''),
      ClientMoPayment_14: getNullableDataValue(data.ClientMoPayment_14, ''),
      ClientMoPayment_15: getNullableDataValue(data.ClientMoPayment_15, ''),
      ClientMoPayment_16: getNullableDataValue(data.ClientMoPayment_16, ''),
      ClientMoPaidTotal: getNullableDataValue(data.ClientMoPaidTotal, ''),
      ClientMoPaid1: getNullableDateValue(data.ClientMoPaid1, ''),
      ClientMoPaid2: getNullableDateValue(data.ClientMoPaid2, ''),
      ClientMoPaid3: getNullableDateValue(data.ClientMoPaid3, ''),
      ClientMoPaid4: getNullableDateValue(data.ClientMoPaid4, ''),
      ClientMoPaid5: getNullableDateValue(data.ClientMoPaid5, ''),
      ClientMoPaid6: getNullableDateValue(data.ClientMoPaid6, ''),
      ClientMoPaid7: getNullableDateValue(data.ClientMoPaid7, ''),
      ClientMoPaid8: getNullableDateValue(data.ClientMoPaid8, ''),
      ClientMoPaid9: getNullableDateValue(data.ClientMoPaid9, ''),
      ClientMoPaid_10: getNullableDateValue(data.ClientMoPaid_10, ''),
      ClientMoPaid_11: getNullableDateValue(data.ClientMoPaid_11, ''),
      ClientMoPaid_12: getNullableDateValue(data.ClientMoPaid_12, ''),
      ClientMoPaid_13: getNullableDateValue(data.ClientMoPaid_13, ''),
      ClientMoPaid_14: getNullableDateValue(data.ClientMoPaid_14, ''),
      ClientMoPaid_15: getNullableDateValue(data.ClientMoPaid_15, ''),
      ClientMoPaid_16: getNullableDateValue(data.ClientMoPaid_16, ''),
      FirmClient1: getNullableDataValue(data.FirmClient1, ''),
      FirmClient2: getNullableDataValue(data.FirmClient2, ''),
      FirmClient3: getNullableDataValue(data.FirmClient3, ''),
      FirmClient4: getNullableDataValue(data.FirmClient4, ''),
      FirmClient5: getNullableDataValue(data.FirmClient5, ''),
      FirmClient6: getNullableDataValue(data.FirmClient6, ''),
      FirmClient7: getNullableDataValue(data.FirmClient7, ''),
      FirmClient8: getNullableDataValue(data.FirmClient8, ''),
      FirmClient9: getNullableDataValue(data.FirmClient9, ''),
      FirmClient_10: getNullableDataValue(data.FirmClient_10, ''),
      FirmClient_11: getNullableDataValue(data.FirmClient_11, ''),
      FirmClient_12: getNullableDataValue(data.FirmClient_12, ''),
      FirmClient_13: getNullableDataValue(data.FirmClient_13, ''),
      FirmClient_14: getNullableDataValue(data.FirmClient_14, ''),
      FirmClient_15: getNullableDataValue(data.FirmClient_15, ''),
      FirmClient_16: getNullableDataValue(data.FirmClient_16, ''),
      FirmClientTotal: getNullableDataValue(data.FirmClientTotal, ''),
      FirmPaid1: getNullableDataValue(data.FirmPaid1, ''),
      FirmPaid2: getNullableDataValue(data.FirmPaid2, ''),
      FirmPaid3: getNullableDataValue(data.FirmPaid3, ''),
      FirmPaid4: getNullableDataValue(data.FirmPaid4, ''),
      FirmPaid5: getNullableDataValue(data.FirmPaid5, ''),
      FirmPaid6: getNullableDataValue(data.FirmPaid6, ''),
      FirmPaid7: getNullableDataValue(data.FirmPaid7, ''),
      FirmPaid8: getNullableDataValue(data.FirmPaid8, ''),
      FirmPaid9: getNullableDataValue(data.FirmPaid9, ''),
      FirmPaid_10: getNullableDataValue(data.FirmPaid_10, ''),
      FirmPaid_11: getNullableDataValue(data.FirmPaid_11, ''),
      FirmPaid_12: getNullableDataValue(data.FirmPaid_12, ''),
      FirmPaid_13: getNullableDataValue(data.FirmPaid_13, ''),
      FirmPaid_14: getNullableDataValue(data.FirmPaid_14, ''),
      FirmPaid_15: getNullableDataValue(data.FirmPaid_15, ''),
      FirmPaid_16: getNullableDataValue(data.FirmPaid_16, ''),
      FirmPaidTotal: getNullableDataValue(data.FirmPaidTotal, ''),
      NSF2: getNullableDataValue(data.NSF2, ''),
      NSF3: getNullableDataValue(data.NSF3, ''),
      NSF4: getNullableDataValue(data.NSF4, ''),
      NSF5: getNullableDataValue(data.NSF5, ''),
      NSF6: getNullableDataValue(data.NSF6, ''),
      NSF7: getNullableDataValue(data.NSF7, ''),
      NSF8: getNullableDataValue(data.NSF8, ''),
      NSF9: getNullableDataValue(data.NSF9, ''),
      NSF10: getNullableDataValue(data.NSF10, ''),
      NSF11: getNullableDataValue(data.NSF11, ''),
      NSF12: getNullableDataValue(data.NSF12, ''),
      NSF13: getNullableDataValue(data.NSF13, ''),
      NSF14: getNullableDataValue(data.NSF14, ''),
      NSF15: getNullableDataValue(data.NSF15, ''),
      NSF16: getNullableDataValue(data.NSF16, ''),
      NSF1: getNullableDataValue(data.NSF1, ''),
      TrustPayor1: getNullableDataValue(data.TrustPayor1, ''),
      TrustPayor2: getNullableDataValue(data.TrustPayor2, ''),
      TrustPayor3: getNullableDataValue(data.TrustPayor3, ''),
      TrustPayor4: getNullableDataValue(data.TrustPayor4, ''),
      TrustPayor5: getNullableDataValue(data.TrustPayor5, ''),
      TrustPayor6: getNullableDataValue(data.TrustPayor6, ''),
      TrustAmtInPurp1: getNullableDataValue(data.TrustAmtInPurp1, ''),
      TrustAmtInPurp2: getNullableDataValue(data.TrustAmtInPurp2, ''),
      TrustAmtInPurp3: getNullableDataValue(data.TrustAmtInPurp3, ''),
      TrustAmtInPurp4: getNullableDataValue(data.TrustAmtInPurp4, ''),
      TrustAmtInPurp5: getNullableDataValue(data.TrustAmtInPurp5, ''),
      TrustAmtInPurp6: getNullableDataValue(data.TrustAmtInPurp6, ''),
      TrustAmtIn1: getNullableDataValue(data.TrustAmtIn1, ''),
      TrustAmtIn2: getNullableDataValue(data.TrustAmtIn2, ''),
      TrustAmtIn3: getNullableDataValue(data.TrustAmtIn3, ''),
      TrustAmtIn4: getNullableDataValue(data.TrustAmtIn4, ''),
      TrustAmtIn5: getNullableDataValue(data.TrustAmtIn5, ''),
      TrustAmtIn6: getNullableDataValue(data.TrustAmtIn6, ''),
      TrustBalance: getNullableDataValue(data.TrustBalance, ''),
      TrustInDate1: getNullableDateValue(data.TrustInDate1, ''),
      TrustInDate2: getNullableDateValue(data.TrustInDate2, ''),
      TrustInDate3: getNullableDateValue(data.TrustInDate3, ''),
      TrustInDate4: getNullableDateValue(data.TrustInDate4, ''),
      TrustInDate5: getNullableDateValue(data.TrustInDate5, ''),
      TrustInDate6: getNullableDateValue(data.TrustInDate6, ''),





    });

    console.log(['SettlementDue', form.get('SettlementDue'), data.SettlementDue]);

    this.pushFormValues(form, data, service);
  }
  private pushFormValues(form: FormGroup, data: any, service: OpportunityService) {
    const intakeFormData = this.setIntakeFormData(data.opportunityId);
    const controls = form.controls;
    for (const property in controls) {
      if (controls.hasOwnProperty(property)) {
        controls[property].setAsyncValidators(CustomValidator.validate(
          service,
          data.opportunityId,
          intakeFormData[property],
        ));
      }
    }
  }
}
