import { Component, OnInit, Input, ChangeDetectionStrategy } from '@angular/core';
import { FormGroup, FormBuilder } from '@angular/forms';
import { Observable, Subject } from 'rxjs';
import { getNullableDateValue, getNullableDataValue } from '../../../../../../../@core/utils/helpers';
import { OpportunityService } from '../../../../../../../@core/backend/common/services/opportunity.service';
import { CustomValidator } from '../../../../../../../@core/backend/common/services/validation.service';
import { takeUntil } from 'rxjs/operators';
@Component({
    selector: 'ngx-p65-demand',
    templateUrl: './p65-demand.component.html',
    styleUrls: ['./p65-demand.component.scss'],
})
export class P65DemandTabComponent implements OnInit {
    protected readonly unsubscribe$ = new Subject<void>();
    data: Observable<any>;
    form: FormGroup;
    @Input() service: OpportunityService;
    @Input() id: string;

    constructor(private fb: FormBuilder) { }

    ngOnInit() {
        this.form = this.initForm(this.fb);
        this.data = this.service.getDemandP65(this.id).pipe(takeUntil(this.unsubscribe$));
        this.data.subscribe(d => {
            this.setFormValues(this.form, d, this.service);
        })
    }

    private setIntakeFormData(opportunityId: String) {
        return {
            ClientID: {
                table: 'opportunity',
                column: 'ClientID',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            P65_60Upload: {
                table: 'Law',
                column: 'P65_60Upload',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            P65Plus: {
                table: 'Law',
                column: 'P65Plus',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            BKSchedulesDue: {
                table: 'CaseInfo',
                column: 'BKSchedulesDue',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            dbtoffer1: {
                table: 'DebtorInfo',
                column: 'dbtoffer1',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Settled_20: {
                table: 'Tracking',
                column: 'Settled_20',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Con1: {
                table: 'TransTracking',
                column: 'Con1',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Disc1: {
                table: 'TransTracking',
                column: 'Disc1',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            ClientDoc1: {
                table: 'Tracking',
                column: 'ClientDoc1',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            DiscLong1: {
                table: 'TransTracking',
                column: 'DiscLong1',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Dacc1: {
                table: 'DebtorBalances',
                column: 'Dacc1',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Daccnumb1: {
                table: 'DebtorBalances',
                column: 'Daccnumb1',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            InProcess1: {
                table: 'TransTracking',
                column: 'InProcess1',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Lconord1: {
                table: 'TransTracking',
                column: 'Lconord1',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            AsgnSatus1: {
                table: 'TransTracking',
                column: 'AsgnSatus1',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            StatusDisc1: {
                table: 'TransTracking',
                column: 'StatusDisc1',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            SubStatus1: {
                table: 'TransTracking',
                column: 'SubStatus1',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Step1CompletedBy: {
                table: 'Tracking',
                column: 'Step1CompletedBy',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            SettleType1: {
                table: 'Tracking',
                column: 'SettleType1',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Settled1: {
                table: 'Tracking',
                column: 'Settled1',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            SettledAmt1: {
                table: 'Tracking',
                column: 'SettledAmt1',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Con2: {
                table: 'TransTracking',
                column: 'Con2',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Disc2: {
                table: 'TransTracking',
                column: 'Disc2',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            ClientDoc2: {
                table: 'Tracking',
                column: 'ClientDoc2',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            DisLong2: {
                table: 'TransTracking',
                column: 'DisLong2',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Dacc2: {
                table: 'DebtorBalances',
                column: 'Dacc2',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Daccnumb2: {
                table: 'DebtorBalances',
                column: 'Daccnumb2',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            INProcess2: {
                table: 'TransTracking',
                column: 'INProcess2',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Lconrecv2: {
                table: 'TransTracking',
                column: 'Lconrecv2',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            AsgnSatus2: {
                table: 'TransTracking',
                column: 'AsgnSatus2',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            StatusDisc2: {
                table: 'TransTracking',
                column: 'StatusDisc2',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            SubStatus2: {
                table: 'TransTracking',
                column: 'SubStatus2',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Step2CompletedBy: {
                table: 'Tracking',
                column: 'Step2CompletedBy',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            SettleType2: {
                table: 'Tracking',
                column: 'SettleType2',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Settled2: {
                table: 'Tracking',
                column: 'Settled2',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            SettledAmt2: {
                table: 'Tracking',
                column: 'SettledAmt2',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            con3: {
                table: 'TransTracking',
                column: 'con3',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Disc3: {
                table: 'TransTracking',
                column: 'Disc3',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            ClientDoc3: {
                table: 'Tracking',
                column: 'ClientDoc3',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            DiscLong3: {
                table: 'TransTracking',
                column: 'DiscLong3',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            dacc3: {
                table: 'DebtorBalances',
                column: 'dacc3',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            daccnumb3: {
                table: 'DebtorBalances',
                column: 'daccnumb3',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            InProcess3: {
                table: 'TransTracking',
                column: 'InProcess3',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Lconrecv3: {
                table: 'TransTracking',
                column: 'Lconrecv3',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            AsgnSatus3: {
                table: 'TransTracking',
                column: 'AsgnSatus3',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            StatusDisc3: {
                table: 'TransTracking',
                column: 'StatusDisc3',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            SubStatus3: {
                table: 'TransTracking',
                column: 'SubStatus3',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Step3CompletedBy: {
                table: 'Tracking',
                column: 'Step3CompletedBy',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            SettleType3: {
                table: 'Tracking',
                column: 'SettleType3',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Settled3: {
                table: 'Tracking',
                column: 'Settled3',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            SettledAmt3: {
                table: 'Tracking',
                column: 'SettledAmt3',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            con4: {
                table: 'TransTracking',
                column: 'con4',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Disc4: {
                table: 'TransTracking',
                column: 'Disc4',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            ClientDoc4: {
                table: 'Tracking',
                column: 'ClientDoc4',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            DiscLong4: {
                table: 'TransTracking',
                column: 'DiscLong4',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            dacc4: {
                table: 'DebtorBalances',
                column: 'dacc4',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            daccnumb4: {
                table: 'DebtorBalances',
                column: 'daccnumb4',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            InProcess4: {
                table: 'TransTracking',
                column: 'InProcess4',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Lconrecv4: {
                table: 'TransTracking',
                column: 'Lconrecv4',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            AsgnSatus4: {
                table: 'TransTracking',
                column: 'AsgnSatus4',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            StatusDisc4: {
                table: 'TransTracking',
                column: 'StatusDisc4',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            SubStatus4: {
                table: 'TransTracking',
                column: 'SubStatus4',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Step4CompletedBy: {
                table: 'Tracking',
                column: 'Step4CompletedBy',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            SettleType4: {
                table: 'Tracking',
                column: 'SettleType4',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Settle4: {
                table: 'Tracking',
                column: 'Settle4',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            SettledAmt4: {
                table: 'Tracking',
                column: 'SettledAmt4',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            con5: {
                table: 'TransTracking',
                column: 'con5',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Disc5: {
                table: 'TransTracking',
                column: 'Disc5',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            ClientDoc5: {
                table: 'Tracking',
                column: 'ClientDoc5',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            DiscLong5: {
                table: 'TransTracking',
                column: 'DiscLong5',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            dacc5: {
                table: 'DebtorBalances',
                column: 'dacc5',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            daccnumb5: {
                table: 'DebtorBalances',
                column: 'daccnumb5',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            InProcess5: {
                table: 'TransTracking',
                column: 'InProcess5',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Lconrecv5: {
                table: 'TransTracking',
                column: 'Lconrecv5',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            AsgnSatus5: {
                table: 'TransTracking',
                column: 'AsgnSatus5',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            StatusDisc5: {
                table: 'TransTracking',
                column: 'StatusDisc5',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            SubStatus5: {
                table: 'TransTracking',
                column: 'SubStatus5',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Step5CompletedBy: {
                table: 'Tracking',
                column: 'Step5CompletedBy',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            SettleType5: {
                table: 'Tracking',
                column: 'SettleType5',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Settled5: {
                table: 'Tracking',
                column: 'Settled5',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            SettledAmt5: {
                table: 'Tracking',
                column: 'SettledAmt5',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            con6: {
                table: 'TransTracking',
                column: 'con6',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Disc6: {
                table: 'TransTracking',
                column: 'Disc6',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            ClientDoc6: {
                table: 'Tracking',
                column: 'ClientDoc6',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            DiscLong6: {
                table: 'TransTracking',
                column: 'DiscLong6',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            dacc6: {
                table: 'DebtorBalances',
                column: 'dacc6',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            daccnumb6: {
                table: 'DebtorBalances',
                column: 'daccnumb6',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            InProcess6: {
                table: 'TransTracking',
                column: 'InProcess6',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Lconrecv6: {
                table: 'TransTracking',
                column: 'Lconrecv6',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            AsgnSatus6: {
                table: 'TransTracking',
                column: 'AsgnSatus6',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            StatusDisc6: {
                table: 'TransTracking',
                column: 'StatusDisc6',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            SubStatus6: {
                table: 'TransTracking',
                column: 'SubStatus6',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Step6CompletedBy: {
                table: 'Tracking',
                column: 'Step6CompletedBy',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            SettleType6: {
                table: 'Tracking',
                column: 'SettleType6',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Settled6: {
                table: 'Tracking',
                column: 'Settled6',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            SettledAmt6: {
                table: 'Tracking',
                column: 'SettledAmt6',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Defendant1Long: {
                table: 'Parties_Involved',
                column: 'Defendant1Long',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            CEO1: {
                table: 'Parties_Involved',
                column: 'CEO1',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party4address: {
                table: 'Parties_Involved',
                column: 'Party4address',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party4city: {
                table: 'Parties_Involved',
                column: 'Party4city',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party4state: {
                table: 'Parties_Involved',
                column: 'Party4state',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party4zip: {
                table: 'Parties_Involved',
                column: 'Party4zip',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party4misc2: {
                table: 'Parties_Involved',
                column: 'Party4misc2',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Cred1: {
                table: 'Law',
                column: 'Cred1',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party3co: {
                table: 'Parties_Involved',
                column: 'Party3co',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party3name: {
                table: 'Parties_Involved',
                column: 'Party3name',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party3address: {
                table: 'Parties_Involved',
                column: 'Party3address',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party3city: {
                table: 'Parties_Involved',
                column: 'Party3city',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party3state: {
                table: 'Parties_Involved',
                column: 'Party3state',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party3zip: {
                table: 'Parties_Involved',
                column: 'Party3zip',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Cred2: {
                table: 'Law',
                column: 'Cred2',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party5Co: {
                table: 'Parties_Involved',
                column: 'Party5Co',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party5name: {
                table: 'Parties_Involved',
                column: 'Party5name',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party5Add: {
                table: 'Parties_Involved',
                column: 'Party5Add',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party5City: {
                table: 'Parties_Involved',
                column: 'Party5City',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party5State: {
                table: 'Parties_Involved',
                column: 'Party5State',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party5zip: {
                table: 'Parties_Involved',
                column: 'Party5zip',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party1Co: {
                table: 'Parties_Involved',
                column: 'Party1Co',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party1Name: {
                table: 'Parties_Involved',
                column: 'Party1Name',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party1phone: {
                table: 'Parties_Involved',
                column: 'Party1phone',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party1direct: {
                table: 'Parties_Involved',
                column: 'Party1direct',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party1email: {
                table: 'Parties_Involved',
                column: 'Party1email',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            PlaintiffPhoneAcquire: {
                table: 'Law',
                column: 'PlaintiffPhoneAcquire',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            CRED1PROOF: {
                table: 'Law',
                column: 'CRED1PROOF',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party2Co: {
                table: 'Parties_Involved',
                column: 'Party2Co',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party2Name: {
                table: 'Parties_Involved',
                column: 'Party2Name',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party2direct: {
                table: 'Parties_Involved',
                column: 'Party2direct',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party2phone: {
                table: 'Parties_Involved',
                column: 'Party2phone',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party2email: {
                table: 'Parties_Involved',
                column: 'Party2email',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            PMTDeclaration1: {
                table: 'Law',
                column: 'PMTDeclaration1',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Cred2Proof: {
                table: 'Law',
                column: 'Cred2Proof',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Step1Completed: {
                table: 'Tracking',
                column: 'Step1Completed',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            ParaLegal1: {
                table: 'Parties_Involved',
                column: 'ParaLegal1',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Step2Completed: {
                table: 'Tracking',
                column: 'Step2Completed',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            ParaLegal2: {
                table: 'Parties_Involved',
                column: 'ParaLegal2',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Step3Completed: {
                table: 'Tracking',
                column: 'Step3Completed',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            ProcessorName: {
                table: 'Parties_Involved',
                column: 'ProcessorName',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            StageDisposition1: {
                table: 'SalesStage',
                column: 'StageDisposition1',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            SalesFollow1: {
                table: 'SalesStage',
                column: 'SalesFollow1',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party2misc1: {
                table: 'Parties_Involved',
                column: 'Party2misc1',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party2state: {
                table: 'Parties_Involved',
                column: 'Party2state',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party3Co: {
                table: 'Parties_Involved',
                column: 'Party3Co',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party3Name: {
                table: 'Parties_Involved',
                column: 'Party3Name',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            Party3misc1: {
                table: 'Parties_Involved',
                column: 'Party3misc1',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            TCPAFirstComplaintDate: {
                table: 'Law',
                column: 'TCPAFirstComplaintDate',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            TcpaLastComplaintDate: {
                table: 'Law',
                column: 'TcpaLastComplaintDate',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            TCPANumberCalls: {
                table: 'Law',
                column: 'TCPANumberCalls',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            TcpaDemandDate: {
                table: 'Law',
                column: 'TcpaDemandDate',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            TCPAPostDemand: {
                table: 'Law',
                column: 'TCPAPostDemand',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            TCPAREVOCATIONDATE: {
                table: 'Law',
                column: 'TCPAREVOCATIONDATE',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            TCPAPostRevo: {
                table: 'Law',
                column: 'TCPAPostRevo',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            TCPAPostSettle: {
                table: 'Law',
                column: 'TCPAPostSettle',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            TcpaDemandAmt: {
                table: 'Law',
                column: 'TcpaDemandAmt',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            TcpaOffenderPhone1: {
                table: 'Law',
                column: 'TcpaOffenderPhone1',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            TcpaOffenderPhone2: {
                table: 'Law',
                column: 'TcpaOffenderPhone2',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            TcpaOffenderPhone3: {
                table: 'Law',
                column: 'TcpaOffenderPhone3',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            TcpaOffenderPhone4: {
                table: 'Law',
                column: 'TcpaOffenderPhone4',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            TcpaOffenderPhone5: {
                table: 'Law',
                column: 'TcpaOffenderPhone5',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            TcpaOffenderPhone6: {
                table: 'Law',
                column: 'TcpaOffenderPhone6',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            TcpaOffenderPhone7: {
                table: 'Law',
                column: 'TcpaOffenderPhone7',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            TcpaOffenderPhone8: {
                table: 'Law',
                column: 'TcpaOffenderPhone8',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            TcpaOffenderPhone9: {
                table: 'Law',
                column: 'TcpaOffenderPhone9',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            TcpaOffenderPhone10: {
                table: 'Law',
                column: 'TcpaOffenderPhone10',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            RegX1: {
                table: 'Law',
                column: 'RegX1',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            RegX2: {
                table: 'Law',
                column: 'RegX2',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            RegX3: {
                table: 'Law',
                column: 'RegX3',
                identifier: opportunityId,
                key: 'OpportunityId',
            },
            RegX4: {
                table: 'Law',
                column: 'RegX4',
                identifier: opportunityId,
                key: 'OpportunityId',
            },













        }
    }


    initForm(fb: FormBuilder): FormGroup {

        const form = fb.group({
            Step6CompletedBy: fb.control(''),
            Settle6: fb.control(''),
            Step5CompletedBy: fb.control(''),
            Settle4: fb.control(''),
            Settle5: fb.control(''),
            Step4CompletedBy: fb.control(''),
            Step3CompletedBy: fb.control(''),
            ClientID: fb.control(''),
            P65_60Upload: fb.control(''),
            P65Plus: fb.control(''),
            BKSchedulesDue: fb.control(''),
            dbtoffer1: fb.control(''),
            Settled_20: fb.control(''),
            Con1: fb.control(''),
            Disc1: fb.control(''),
            ClientDoc1: fb.control(''),
            DiscLong1: fb.control(''),
            Dacc1: fb.control(''),
            Daccnumb1: fb.control(''),
            InProcess1: fb.control(''),
            Lconord1: fb.control(''),
            AsgnSatus1: fb.control(''),
            StatusDisc1: fb.control(''),
            SubStatus1: fb.control(''),
            Step1CompletedBy: fb.control(''),
            SettleType1: fb.control(''),
            Settled1: fb.control(''),
            SettledAmt1: fb.control(''),
            Con2: fb.control(''),
            Disc2: fb.control(''),
            ClientDoc2: fb.control(''),
            DisLong2: fb.control(''),
            Dacc2: fb.control(''),
            Daccnumb2: fb.control(''),
            INProcess2: fb.control(''),
            Lconrecv2: fb.control(''),
            AsgnSatus2: fb.control(''),
            StatusDisc2: fb.control(''),
            SubStatus2: fb.control(''),
            Step2CompletedBy: fb.control(''),
            SettleType2: fb.control(''),
            Settled2: fb.control(''),
            SettledAmt2: fb.control(''),
            con3: fb.control(''),
            Disc3: fb.control(''),
            ClientDoc3: fb.control(''),
            DiscLong3: fb.control(''),
            dacc3: fb.control(''),
            daccnumb3: fb.control(''),
            InProcess3: fb.control(''),
            Lconrecv3: fb.control(''),
            AsgnSatus3: fb.control(''),
            StatusDisc3: fb.control(''),
            SubStatus3: fb.control(''),
            SettleType3: fb.control(''),
            Settled3: fb.control(''),
            SettledAmt3: fb.control(''),
            con4: fb.control(''),
            Disc4: fb.control(''),
            ClientDoc4: fb.control(''),
            DiscLong4: fb.control(''),
            dacc4: fb.control(''),
            daccnumb4: fb.control(''),
            InProcess4: fb.control(''),
            Lconrecv4: fb.control(''),
            AsgnSatus4: fb.control(''),
            StatusDisc4: fb.control(''),
            SubStatus4: fb.control(''),
            SettleType4: fb.control(''),
            SettledAmt4: fb.control(''),
            con5: fb.control(''),
            Disc5: fb.control(''),
            ClientDoc5: fb.control(''),
            DiscLong5: fb.control(''),
            dacc5: fb.control(''),
            daccnumb5: fb.control(''),
            InProcess5: fb.control(''),
            Lconrecv5: fb.control(''),
            AsgnSatus5: fb.control(''),
            StatusDisc5: fb.control(''),
            SubStatus5: fb.control(''),
            SettleType5: fb.control(''),
            Settled5: fb.control(''),
            SettledAmt5: fb.control(''),
            con6: fb.control(''),
            Disc6: fb.control(''),
            ClientDoc6: fb.control(''),
            DiscLong6: fb.control(''),
            dacc6: fb.control(''),
            daccnumb6: fb.control(''),
            InProcess6: fb.control(''),
            Lconrecv6: fb.control(''),
            AsgnSatus6: fb.control(''),
            StatusDisc6: fb.control(''),
            SubStatus6: fb.control(''),
            SettleType6: fb.control(''),
            Settled6: fb.control(''),
            SettledAmt6: fb.control(''),
            Defendant1Long: fb.control(''),
            CEO1: fb.control(''),
            Party4address: fb.control(''),
            Party4city: fb.control(''),
            Party4state: fb.control(''),
            Party4zip: fb.control(''),
            Party4misc2: fb.control(''),
            Cred1: fb.control(''),
            Party3co: fb.control(''),
            Party3name: fb.control(''),
            Party3address: fb.control(''),
            Party3city: fb.control(''),
            Party3state: fb.control(''),
            Party3zip: fb.control(''),
            Cred2: fb.control(''),
            Party5Co: fb.control(''),
            Party5name: fb.control(''),
            Party5Add: fb.control(''),
            Party5City: fb.control(''),
            Party5State: fb.control(''),
            Party5zip: fb.control(''),
            Party1Co: fb.control(''),
            Party1Name: fb.control(''),
            Party1phone: fb.control(''),
            Party1direct: fb.control(''),
            Party1email: fb.control(''),
            PlaintiffPhoneAcquire: fb.control(''),
            CRED1PROOF: fb.control(''),
            Party2Co: fb.control(''),
            Party2Name: fb.control(''),
            Party2direct: fb.control(''),
            Party2phone: fb.control(''),
            Party2email: fb.control(''),
            PMTDeclaration1: fb.control(''),
            Cred2Proof: fb.control(''),
            Step1Completed: fb.control(''),
            ParaLegal1: fb.control(''),
            Step2Completed: fb.control(''),
            ParaLegal2: fb.control(''),
            Step3Completed: fb.control(''),
            ProcessorName: fb.control(''),
            StageDisposition1: fb.control(''),
            SalesFollow1: fb.control(''),
            Party2misc1: fb.control(''),
            Party2state: fb.control(''),
            Party3Name: fb.control(''),
            Party3misc1: fb.control(''),
            TCPAFirstComplaintDate: fb.control(''),
            TcpaLastComplaintDate: fb.control(''),
            TCPANumberCalls: fb.control(''),
            TcpaDemandDate: fb.control(''),
            TCPAPostDemand: fb.control(''),
            TCPAREVOCATIONDATE: fb.control(''),
            TCPAPostRevo: fb.control(''),
            TCPAPostSettle: fb.control(''),
            TcpaDemandAmt: fb.control(''),
            TcpaOffenderPhone1: fb.control(''),
            TcpaOffenderPhone2: fb.control(''),
            TcpaOffenderPhone3: fb.control(''),
            TcpaOffenderPhone4: fb.control(''),
            TcpaOffenderPhone5: fb.control(''),
            TcpaOffenderPhone6: fb.control(''),
            TcpaOffenderPhone7: fb.control(''),
            TcpaOffenderPhone8: fb.control(''),
            TcpaOffenderPhone9: fb.control(''),
            TcpaOffenderPhone10: fb.control(''),
            RegX1: fb.control(''),
            RegX2: fb.control(''),
            RegX3: fb.control(''),
            RegX4: fb.control(''),



        }, { updateOn: 'blur' });
        return form;
    }


    setFormValues(form: FormGroup, data: any, service: OpportunityService) {
        form.setValue({
            Party3misc1: getNullableDataValue(data.Party3misc1, ''),
            Party2state: getNullableDataValue(data.Party2state, ''),
            Party2misc1: getNullableDataValue(data.Party2misc1, ''),
            Settle6: getNullableDateValue(data.Settle6, ''),
            Settle5: getNullableDateValue(data.Settle5, ''),
            ClientID: getNullableDataValue(data.ClientID, ''),
            P65_60Upload: getNullableDataValue(data.P65_60Upload, ''),
            P65Plus: getNullableDataValue(data.P65Plus, ''),
            BKSchedulesDue: getNullableDataValue(data.BKSchedulesDue, ''),
            dbtoffer1: getNullableDataValue(data.dbtoffer1, ''),
            Settled_20: getNullableDataValue(data.Settled_20, ''),
            Con1: getNullableDataValue(data.Con1, ''),
            Disc1: getNullableDataValue(data.Disc1, ''),
            ClientDoc1: getNullableDataValue(data.ClientDoc1, ''),
            DiscLong1: getNullableDataValue(data.DiscLong1, ''),
            Dacc1: getNullableDataValue(data.Dacc1, ''),
            Daccnumb1: getNullableDataValue(data.Daccnumb1, ''),
            InProcess1: getNullableDataValue(data.InProcess1, ''),
            Lconord1: getNullableDataValue(data.Lconord1, ''),
            AsgnSatus1: getNullableDataValue(data.AsgnSatus1, ''),
            StatusDisc1: getNullableDataValue(data.StatusDisc1, ''),
            SubStatus1: getNullableDataValue(data.SubStatus1, ''),
            Step1CompletedBy: getNullableDataValue(data.Step1CompletedBy, ''),
            SettleType1: getNullableDataValue(data.SettleType1, ''),
            Settled1: getNullableDataValue(data.Settled1, ''),
            SettledAmt1: getNullableDataValue(data.SettledAmt1, ''),
            Con2: getNullableDataValue(data.Con2, ''),
            Disc2: getNullableDataValue(data.Disc2, ''),
            ClientDoc2: getNullableDataValue(data.ClientDoc2, ''),
            DisLong2: getNullableDataValue(data.DisLong2, ''),
            Dacc2: getNullableDataValue(data.Dacc2, ''),
            Daccnumb2: getNullableDataValue(data.Daccnumb2, ''),
            INProcess2: getNullableDataValue(data.INProcess2, ''),
            Lconrecv2: getNullableDataValue(data.Lconrecv2, ''),
            AsgnSatus2: getNullableDataValue(data.AsgnSatus2, ''),
            StatusDisc2: getNullableDataValue(data.StatusDisc2, ''),
            SubStatus2: getNullableDataValue(data.SubStatus2, ''),
            Step2CompletedBy: getNullableDataValue(data.Step2CompletedBy, ''),
            SettleType2: getNullableDataValue(data.SettleType2, ''),
            Settled2: getNullableDataValue(data.Settled2, ''),
            SettledAmt2: getNullableDataValue(data.SettledAmt2, ''),
            con3: getNullableDataValue(data.con3, ''),
            Disc3: getNullableDataValue(data.Disc3, ''),
            ClientDoc3: getNullableDataValue(data.ClientDoc3, ''),
            DiscLong3: getNullableDataValue(data.DiscLong3, ''),
            dacc3: getNullableDataValue(data.dacc3, ''),
            daccnumb3: getNullableDataValue(data.daccnumb3, ''),
            InProcess3: getNullableDataValue(data.InProcess3, ''),
            Lconrecv3: getNullableDataValue(data.Lconrecv3, ''),
            AsgnSatus3: getNullableDataValue(data.AsgnSatus3, ''),
            StatusDisc3: getNullableDataValue(data.StatusDisc3, ''),
            SubStatus3: getNullableDataValue(data.SubStatus3, ''),
            Step3CompletedBy: getNullableDataValue(data.Step3CompletedBy, ''),
            SettleType3: getNullableDataValue(data.SettleType3, ''),
            Settled3: getNullableDataValue(data.Settled3, ''),
            SettledAmt3: getNullableDataValue(data.SettledAmt3, ''),
            con4: getNullableDataValue(data.con4, ''),
            Disc4: getNullableDataValue(data.Disc4, ''),
            ClientDoc4: getNullableDataValue(data.ClientDoc4, ''),
            DiscLong4: getNullableDataValue(data.DiscLong4, ''),
            dacc4: getNullableDataValue(data.dacc4, ''),
            daccnumb4: getNullableDataValue(data.daccnumb4, ''),
            InProcess4: getNullableDataValue(data.InProcess4, ''),
            Lconrecv4: getNullableDataValue(data.Lconrecv4, ''),
            AsgnSatus4: getNullableDataValue(data.AsgnSatus4, ''),
            StatusDisc4: getNullableDataValue(data.StatusDisc4, ''),
            SubStatus4: getNullableDataValue(data.SubStatus4, ''),
            Step4CompletedBy: getNullableDataValue(data.Step4CompletedBy, ''),
            SettleType4: getNullableDataValue(data.SettleType4, ''),
            Settle4: getNullableDataValue(data.Settle4, ''),
            SettledAmt4: getNullableDataValue(data.SettledAmt4, ''),
            con5: getNullableDataValue(data.con5, ''),
            Disc5: getNullableDataValue(data.Disc5, ''),
            ClientDoc5: getNullableDataValue(data.ClientDoc5, ''),
            DiscLong5: getNullableDataValue(data.DiscLong5, ''),
            dacc5: getNullableDataValue(data.dacc5, ''),
            daccnumb5: getNullableDataValue(data.daccnumb5, ''),
            InProcess5: getNullableDataValue(data.InProcess5, ''),
            Lconrecv5: getNullableDataValue(data.Lconrecv5, ''),
            AsgnSatus5: getNullableDataValue(data.AsgnSatus5, ''),
            StatusDisc5: getNullableDataValue(data.StatusDisc5, ''),
            SubStatus5: getNullableDataValue(data.SubStatus5, ''),
            Step5CompletedBy: getNullableDataValue(data.Step5CompletedBy, ''),
            SettleType5: getNullableDataValue(data.SettleType5, ''),
            Settled5: getNullableDataValue(data.Settled5, ''),
            SettledAmt5: getNullableDataValue(data.SettledAmt5, ''),
            con6: getNullableDataValue(data.con6, ''),
            Disc6: getNullableDataValue(data.Disc6, ''),
            ClientDoc6: getNullableDataValue(data.ClientDoc6, ''),
            DiscLong6: getNullableDataValue(data.DiscLong6, ''),
            dacc6: getNullableDataValue(data.dacc6, ''),
            daccnumb6: getNullableDataValue(data.daccnumb6, ''),
            InProcess6: getNullableDataValue(data.InProcess6, ''),
            Lconrecv6: getNullableDataValue(data.Lconrecv6, ''),
            AsgnSatus6: getNullableDataValue(data.AsgnSatus6, ''),
            StatusDisc6: getNullableDataValue(data.StatusDisc6, ''),
            SubStatus6: getNullableDataValue(data.SubStatus6, ''),
            Step6CompletedBy: getNullableDataValue(data.Step6CompletedBy, ''),
            SettleType6: getNullableDataValue(data.SettleType6, ''),
            Settled6: getNullableDataValue(data.Settled6, ''),
            SettledAmt6: getNullableDataValue(data.SettledAmt6, ''),
            Defendant1Long: getNullableDataValue(data.Defendant1Long, ''),
            CEO1: getNullableDataValue(data.CEO1, ''),
            Party4address: getNullableDataValue(data.Party4address, ''),
            Party4city: getNullableDataValue(data.Party4city, ''),
            Party4state: getNullableDataValue(data.Party4state, ''),
            Party4zip: getNullableDataValue(data.Party4zip, ''),
            Party4misc2: getNullableDataValue(data.Party4misc2, ''),
            Cred1: getNullableDataValue(data.Cred1, ''),
            Party3co: getNullableDataValue(data.Party3co, ''),
            Party3name: getNullableDataValue(data.Party3name, ''),
            Party3Name: getNullableDataValue(data.Party3Name, ''),
            Party3address: getNullableDataValue(data.Party3address, ''),
            Party3city: getNullableDataValue(data.Party3city, ''),
            Party3state: getNullableDataValue(data.Party3state, ''),
            Party3zip: getNullableDataValue(data.Party3zip, ''),
            Cred2: getNullableDataValue(data.Cred2, ''),
            Party5Co: getNullableDataValue(data.Party5Co, ''),
            Party5name: getNullableDataValue(data.Party5name, ''),
            Party5Add: getNullableDataValue(data.Party5Add, ''),
            Party5City: getNullableDataValue(data.Party5City, ''),
            Party5State: getNullableDataValue(data.Party5State, ''),
            Party5zip: getNullableDataValue(data.Party5zip, ''),
            Party1Co: getNullableDataValue(data.Party1Co, ''),
            Party1Name: getNullableDataValue(data.Party1Name, ''),
            Party1phone: getNullableDataValue(data.Party1phone, ''),
            Party1direct: getNullableDataValue(data.Party1direct, ''),
            Party1email: getNullableDataValue(data.Party1email, ''),
            PlaintiffPhoneAcquire: getNullableDataValue(data.PlaintiffPhoneAcquire, ''),
            CRED1PROOF: getNullableDataValue(data.CRED1PROOF, ''),
            Party2Co: getNullableDataValue(data.Party2Co, ''),
            Party2Name: getNullableDataValue(data.Party2Name, ''),
            Party2direct: getNullableDataValue(data.Party2direct, ''),
            Party2phone: getNullableDataValue(data.Party2phone, ''),
            Party2email: getNullableDataValue(data.Party2email, ''),
            PMTDeclaration1: getNullableDataValue(data.PMTDeclaration1, ''),
            Cred2Proof: getNullableDataValue(data.Cred2Proof, ''),
            Step1Completed: getNullableDataValue(data.Step1Completed, ''),
            ParaLegal1: getNullableDataValue(data.ParaLegal1, ''),
            Step2Completed: getNullableDataValue(data.Step2Completed, ''),
            ParaLegal2: getNullableDataValue(data.ParaLegal2, ''),
            Step3Completed: getNullableDataValue(data.Step3Completed, ''),
            ProcessorName: getNullableDataValue(data.ProcessorName, ''),
            StageDisposition1: getNullableDataValue(data.StageDisposition1, ''),
            SalesFollow1: getNullableDataValue(data.SalesFollow1, ''),
            TCPAFirstComplaintDate: getNullableDataValue(data.TCPAFirstComplaintDate, ''),
            TcpaLastComplaintDate: getNullableDataValue(data.TcpaLastComplaintDate, ''),
            TCPANumberCalls: getNullableDataValue(data.TCPANumberCalls, ''),
            TcpaDemandDate: getNullableDataValue(data.TcpaDemandDate, ''),
            TCPAPostDemand: getNullableDataValue(data.TCPAPostDemand, ''),
            TCPAREVOCATIONDATE: getNullableDataValue(data.TCPAREVOCATIONDATE, ''),
            TCPAPostRevo: getNullableDataValue(data.TCPAPostRevo, ''),
            TCPAPostSettle: getNullableDataValue(data.TCPAPostSettle, ''),
            TcpaDemandAmt: getNullableDataValue(data.TcpaDemandAmt, ''),
            TcpaOffenderPhone1: getNullableDataValue(data.TcpaOffenderPhone1, ''),
            TcpaOffenderPhone2: getNullableDataValue(data.TcpaOffenderPhone2, ''),
            TcpaOffenderPhone3: getNullableDataValue(data.TcpaOffenderPhone3, ''),
            TcpaOffenderPhone4: getNullableDataValue(data.TcpaOffenderPhone4, ''),
            TcpaOffenderPhone5: getNullableDataValue(data.TcpaOffenderPhone5, ''),
            TcpaOffenderPhone6: getNullableDataValue(data.TcpaOffenderPhone6, ''),
            TcpaOffenderPhone7: getNullableDataValue(data.TcpaOffenderPhone7, ''),
            TcpaOffenderPhone8: getNullableDataValue(data.TcpaOffenderPhone8, ''),
            TcpaOffenderPhone9: getNullableDataValue(data.TcpaOffenderPhone9, ''),
            TcpaOffenderPhone10: getNullableDataValue(data.TcpaOffenderPhone10, ''),
            RegX1: getNullableDataValue(data.RegX1, ''),
            RegX2: getNullableDataValue(data.RegX2, ''),
            RegX3: getNullableDataValue(data.RegX3, ''),
            RegX4: getNullableDataValue(data.RegX4, ''),






        });
        this.pushFormValues(form, data, service);
    }

    private pushFormValues(form: FormGroup, data: any, service: OpportunityService) {
        const intakeFormData = this.setIntakeFormData(data.opportunityId);
        const controls = form.controls;
        for (const property in controls) {
            if (controls.hasOwnProperty(property)) {
                controls[property].setAsyncValidators(CustomValidator.validate(
                    service,
                    data.opportunityId,
                    intakeFormData[property],
                ));
            }
        }
    }

}
