import { Component, OnInit, Input } from '@angular/core';
import { ContactService } from '../../../../../../@core/backend/common/services/contact.service';
import { FormGroup, FormBuilder } from '@angular/forms';
import { Observable } from 'rxjs';
import { getNullableDataValue } from '../../../../../../@core/utils/helpers';
@Component({
    selector: 'ngx-afg-parties-tab',
    templateUrl: './afg-parties.component.html',
    styleUrls: ['./afg-parties.component.scss'],
})
export class AFGPartiesTabComponent implements OnInit {
    accountName: '';
    form: FormGroup;
    @Input() service: ContactService;
    @Input() data: Observable<any>;

    constructor(private fb: FormBuilder) { }

    ngOnInit() {
        this.form = this.initForm(this.fb);
        this.loadAccountTestData(this.form);
    }

    loadAccountTestData(form: FormGroup) {
        const data = {
            link: 'Link',
            edAgent: 'Edit Agent',
            comp: 'Company',
            contact: 'Contact',
            email: 'Email',
            phBus: 'Bus Ph',
            fax: 'Fax',
            cell: 'Cell',
            assistnt: 'assistnt',
            email2: 'Email',
            work: 'Work',
            mob: 'Mobile',
            addy: 'Address',
            state: 'State',
            city: 'City',
            zip: 'Zip',
            bdrId: 'BDR_ID',
            contactId: 'Contact ID',
            accId: 'Acc ID',
            ownerId: 'Owner ID',
            brokerId: 'Broker ID',
            seller: 'Seller',
            phone: 'Phone',
            fax2: 'Fax',
            escEmail: 'Escrow Email',
            link2: 'Link',
            edAgent2: 'Edit Agent',
            comp2: 'Contact',
            email3: 'Email',
            phBus2: 'Bus Ph',
            fax3: 'Fax',
            cell2: 'Cell',
            assistnt2: 'Assistant',
            email4: 'Email',
            work2: 'Work',
            mob2: 'Mobile',
            addy2: 'Address',
            state2: 'State',
            city2: 'City',
            zip2: 'Zip',
            bdrId2: 'BDR_ID',
            contactId2: 'Contact ID',
            accId2: 'Acc ID',
            ownderId2: 'Owner ID',
            brokerId2: 'Broker ID',
            link3: 'Link',
            edAgent3: 'Edit Agent',
            comp3: 'Company',
            contact3: 'Contact',
            email5: 'Email',
            phBus3: 'Bus Ph',
            fax4: 'Fax',
            cell3: 'Cell',
            notes: '...',
            insur1: '...',
            insur2: '...',
            insur3: '...',
            insur4: '...',
            insur5: '...',
            insur6: '...',
            insur7: '...',
            link4: 'Link',
            edAgent4: 'Edit Agent',
            comp4: 'Company',
            contact4: 'Contact',
            email6: 'Email',
            phBus4: 'Bus Ph',
            fax5: 'Fax',
            cell4: 'Cell',
            assist4: 'Assistant',
            work3: '...',
            work4: '...',
            work5: '...',
            apprs1: 'Appraisal',
            apprs2: 'Appraisal',
            apprs3: 'Appraisal',
            email7: 'Email',
            apprs5: 'Appraisal',
            apprs6: 'Appraisal',
            apprs7: 'Appraisal',
            link5: 'contId',
            contId: 'Cont ID',
            comp5: 'Company',
            contact5: 'Contact',
            title: 'Title',
            email8: 'Email',
            phBus5: 'Bus Ph',
            fax6: 'Fax',
            mob3: 'Mobile',
            nmlsNum: 'NMLS#',
            dreNum: 'DRE#',
            bdr: 'BDR',
            addy3: 'Address',
            addy4: 'Address',
            addy5: 'Address',
            addy6: 'Address',
            refer1: 'Referral',
            refer2: 'Referral',
            refer3: 'Referral',
            refer4: 'Referral',
            refer5: 'Referral',
            refer6: 'Referral',
            refer7: 'Referral',
            refer8: 'referral',
            link6: 'Link',
            contId2: 'Cont ID',
            comp6: 'Company',
            contact6: 'Contact',
            title2: 'Title',
            proc6: '...',
            phBus6: 'Bus Ph',
            fax7: 'Fax',
            mob4: 'Mobile',
            accMngr: 'Account Manager',
            userId: 'User ID',
            title3: 'Title',
            phone2: 'Phone Number',
            mob5: 'Mobile',
            fax8: 'Fax',
            email9: 'Email',
            compName: 'Company Name',
            compName2: 'Company Name',
            addy7: 'Address',
            addy8: 'Address',
            addy9: 'Address',
            addy10: 'Address',
            accMngId: 'Account Manager ID',
            mngId: 'Manager ID',
            areaMngId: 'Area Manager ID',
            regiMngId: 'Regional Manager ID',
            vicepId: 'Vice President',
            admin: 'Admin',
            supAdmin: 'Super Admin',
            globAdmin: 'Global Admin',
            miscInput: '...',
        };
        this.setFormValues(form, data);
    }

    initForm(fb: FormBuilder): FormGroup {
        const form = fb.group({
            link: fb.control(''),
            edAgent: fb.control(''),
            comp: fb.control(''),
            contact: fb.control(''),
            email: fb.control(''),
            phBus: fb.control(''),
            fax: fb.control(''),
            cell: fb.control(''),
            assistnt: fb.control(''),
            email2: fb.control(''),
            work: fb.control(''),
            mob: fb.control(''),
            addy: fb.control(''),
            state: fb.control(''),
            city: fb.control(''),
            zip: fb.control(''),
            bdrId: fb.control(''),
            contactId: fb.control(''),
            accId: fb.control(''),
            ownerId: fb.control(''),
            brokerId: fb.control(''),
            seller: fb.control(''),
            phone: fb.control(''),
            fax2: fb.control(''),
            escEmail: fb.control(''),
            link2: fb.control(''),
            edAgent2: fb.control(''),
            comp2: fb.control(''),
            email3: fb.control(''),
            phBus2: fb.control(''),
            fax3: fb.control(''),
            cell2: fb.control(''),
            assistnt2: fb.control(''),
            email4: fb.control(''),
            work2: fb.control(''),
            mob2: fb.control(''),
            addy2: fb.control(''),
            state2: fb.control(''),
            city2: fb.control(''),
            zip2: fb.control(''),
            bdrId2: fb.control(''),
            contactId2: fb.control(''),
            accId2: fb.control(''),
            ownderId2: fb.control(''),
            brokerId2: fb.control(''),
            link3: fb.control(''),
            edAgent3: fb.control(''),
            comp3: fb.control(''),
            contact3: fb.control(''),
            email5: fb.control(''),
            phBus3: fb.control(''),
            fax4: fb.control(''),
            cell3: fb.control(''),
            notes: fb.control(''),
            insur1: fb.control(''),
            insur2: fb.control(''),
            insur3: fb.control(''),
            insur4: fb.control(''),
            insur5: fb.control(''),
            insur6: fb.control(''),
            insur7: fb.control(''),
            link4: fb.control(''),
            edAgent4: fb.control(''),
            comp4: fb.control(''),
            contact4: fb.control(''),
            email6: fb.control(''),
            phBus4: fb.control(''),
            fax5: fb.control(''),
            cell4: fb.control(''),
            assist4: fb.control(''),
            work3: fb.control(''),
            work4: fb.control(''),
            work5: fb.control(''),
            apprs1: fb.control(''),
            apprs2: fb.control(''),
            apprs3: fb.control(''),
            email7: fb.control(''),
            apprs5: fb.control(''),
            apprs6: fb.control(''),
            apprs7: fb.control(''),
            link5: fb.control(''),
            contId: fb.control(''),
            comp5: fb.control(''),
            contact5: fb.control(''),
            title: fb.control(''),
            email8: fb.control(''),
            phBus5: fb.control(''),
            fax6: fb.control(''),
            mob3: fb.control(''),
            nmlsNum: fb.control(''),
            dreNum: fb.control(''),
            bdr: fb.control(''),
            addy3: fb.control(''),
            addy4: fb.control(''),
            addy5: fb.control(''),
            addy6: fb.control(''),
            refer1: fb.control(''),
            refer2: fb.control(''),
            refer3: fb.control(''),
            refer4: fb.control(''),
            refer5: fb.control(''),
            refer6: fb.control(''),
            refer7: fb.control(''),
            refer8: fb.control(''),
            link6: fb.control(''),
            contId2: fb.control(''),
            comp6: fb.control(''),
            contact6: fb.control(''),
            title2: fb.control(''),
            proc6: fb.control(''),
            phBus6: fb.control(''),
            fax7: fb.control(''),
            mob4: fb.control(''),
            accMngr: fb.control(''),
            userId: fb.control(''),
            title3: fb.control(''),
            phone2: fb.control(''),
            mob5: fb.control(''),
            fax8: fb.control(''),
            email9: fb.control(''),
            compName: fb.control(''),
            compName2: fb.control(''),
            addy7: fb.control(''),
            addy8: fb.control(''),
            addy9: fb.control(''),
            addy10: fb.control(''),
            accMngId: fb.control(''),
            mngId: fb.control(''),
            areaMngId: fb.control(''),
            regiMngId: fb.control(''),
            vicepId: fb.control(''),
            admin: fb.control(''),
            supAdmin: fb.control(''),
            globAdmin: fb.control(''),
            miscInput: fb.control(''),
        }, { updateOn: 'blur' });
        return form;
    }

    setFormValues(form: FormGroup, data: any) {
        form.setValue({
            link: getNullableDataValue(data.link, ''),
            edAgent: getNullableDataValue(data.edAgent, ''),
            comp: getNullableDataValue(data.comp, ''),
            contact: getNullableDataValue(data.contact, ''),
            email: getNullableDataValue(data.email, ''),
            phBus: getNullableDataValue(data.phBus, ''),
            fax: getNullableDataValue(data.fax, ''),
            cell: getNullableDataValue(data.cell, ''),
            assistnt: getNullableDataValue(data.assistnt, ''),
            email2: getNullableDataValue(data.email2, ''),
            work: getNullableDataValue(data.work, ''),
            mob: getNullableDataValue(data.mob, ''),
            addy: getNullableDataValue(data.addy, ''),
            state: getNullableDataValue(data.state, ''),
            city: getNullableDataValue(data.city, ''),
            zip: getNullableDataValue(data.zip, ''),
            bdrId: getNullableDataValue(data.bdrId, ''),
            contactId: getNullableDataValue(data.contactId, ''),
            accId: getNullableDataValue(data.accId, ''),
            ownerId: getNullableDataValue(data.ownerId, ''),
            brokerId: getNullableDataValue(data.brokerId, ''),
            seller: getNullableDataValue(data.seller, ''),
            phone: getNullableDataValue(data.phone, ''),
            fax2: getNullableDataValue(data.fax2, ''),
            escEmail: getNullableDataValue(data.escEmail, ''),
            link2: getNullableDataValue(data.link2, ''),
            edAgent2: getNullableDataValue(data.edAgent2, ''),
            comp2: getNullableDataValue(data.comp2, ''),
            email3: getNullableDataValue(data.email3, ''),
            phBus2: getNullableDataValue(data.phBus2, ''),
            fax3: getNullableDataValue(data.fax3, ''),
            cell2: getNullableDataValue(data.cell2, ''),
            assistnt2: getNullableDataValue(data.assistnt2, ''),
            email4: getNullableDataValue(data.email4, ''),
            work2: getNullableDataValue(data.work2, ''),
            mob2: getNullableDataValue(data.mob2, ''),
            addy2: getNullableDataValue(data.addy2, ''),
            state2: getNullableDataValue(data.state2, ''),
            city2: getNullableDataValue(data.city2, ''),
            zip2: getNullableDataValue(data.zip2, ''),
            bdrId2: getNullableDataValue(data.bdrId2, ''),
            contactId2: getNullableDataValue(data.contactId2, ''),
            accId2: getNullableDataValue(data.accId2, ''),
            ownderId2: getNullableDataValue(data.ownerId2, ''),
            brokerId2: getNullableDataValue(data.brokerId2, ''),
            link3: getNullableDataValue(data.link3, ''),
            edAgent3: getNullableDataValue(data.edAgent3, ''),
            comp3: getNullableDataValue(data.comp3, ''),
            contact3: getNullableDataValue(data.contact3, ''),
            email5: getNullableDataValue(data.email5, ''),
            phBus3: getNullableDataValue(data.phBus3, ''),
            fax4: getNullableDataValue(data.fax4, ''),
            cell3: getNullableDataValue(data.cell3, ''),
            notes: getNullableDataValue(data.notes, ''),
            insur1: getNullableDataValue(data.insur1, ''),
            insur2: getNullableDataValue(data.insur2, ''),
            insur3: getNullableDataValue(data.insur3, ''),
            insur4: getNullableDataValue(data.insur4, ''),
            insur5: getNullableDataValue(data.insur5, ''),
            insur6: getNullableDataValue(data.insur6, ''),
            insur7: getNullableDataValue(data.insur7, ''),
            link4: getNullableDataValue(data.link4, ''),
            edAgent4: getNullableDataValue(data.edAgent4, ''),
            comp4: getNullableDataValue(data.comp4, ''),
            contact4: getNullableDataValue(data.contact4, ''),
            email6: getNullableDataValue(data.email6, ''),
            phBus4: getNullableDataValue(data.phBus4, ''),
            fax5: getNullableDataValue(data.fax5, ''),
            cell4: getNullableDataValue(data.cell4, ''),
            assist4: getNullableDataValue(data.assist4, ''),
            work3: getNullableDataValue(data.work3, ''),
            work4: getNullableDataValue(data.work4, ''),
            work5: getNullableDataValue(data.work5, ''),
            apprs1: getNullableDataValue(data.apprs1, ''),
            apprs2: getNullableDataValue(data.apprs2, ''),
            apprs3: getNullableDataValue(data.apprs3, ''),
            email7: getNullableDataValue(data.email7, ''),
            apprs5: getNullableDataValue(data.apprs5, ''),
            apprs6: getNullableDataValue(data.apprs6, ''),
            apprs7: getNullableDataValue(data.apprs7, ''),
            link5: getNullableDataValue(data.link5, ''),
            contId: getNullableDataValue(data.contId, ''),
            comp5: getNullableDataValue(data.comp5, ''),
            contact5: getNullableDataValue(data.contact5, ''),
            title: getNullableDataValue(data.title, ''),
            email8: getNullableDataValue(data.email8, ''),
            phBus5: getNullableDataValue(data.phBus5, ''),
            fax6: getNullableDataValue(data.fax6, ''),
            mob3: getNullableDataValue(data.mob3, ''),
            nmlsNum: getNullableDataValue(data.nmlsNum, ''),
            dreNum: getNullableDataValue(data.dreNum, ''),
            bdr: getNullableDataValue(data.bdr, ''),
            addy3: getNullableDataValue(data.addy3, ''),
            addy4: getNullableDataValue(data.addy4, ''),
            addy5: getNullableDataValue(data.addy5, ''),
            addy6: getNullableDataValue(data.addy6, ''),
            refer1: getNullableDataValue(data.refer1, ''),
            refer2: getNullableDataValue(data.refer2, ''),
            refer3: getNullableDataValue(data.refer3, ''),
            refer4: getNullableDataValue(data.refer4, ''),
            refer5: getNullableDataValue(data.refer5, ''),
            refer6: getNullableDataValue(data.refer6, ''),
            refer7: getNullableDataValue(data.refer7, ''),
            refer8: getNullableDataValue(data.refer8, ''),
            link6: getNullableDataValue(data.link6, ''),
            contId2: getNullableDataValue(data.contId2, ''),
            comp6: getNullableDataValue(data.comp6, ''),
            contact6: getNullableDataValue(data.contact6, ''),
            title2: getNullableDataValue(data.title2, ''),
            proc6: getNullableDataValue(data.proc6, ''),
            phBus6: getNullableDataValue(data.phBus6, ''),
            fax7: getNullableDataValue(data.fax7, ''),
            mob4: getNullableDataValue(data.mob4, ''),
            accMngr: getNullableDataValue(data.accMngr, ''),
            userId: getNullableDataValue(data.userId, ''),
            title3: getNullableDataValue(data.title3, ''),
            phone2: getNullableDataValue(data.phone2, ''),
            mob5: getNullableDataValue(data.mob5, ''),
            fax8: getNullableDataValue(data.fax8, ''),
            email9: getNullableDataValue(data.email9, ''),
            compName: getNullableDataValue(data.compName, ''),
            compName2: getNullableDataValue(data.compName2, ''),
            addy7: getNullableDataValue(data.addy7, ''),
            addy8: getNullableDataValue(data.addy8, ''),
            addy9: getNullableDataValue(data.addy9, ''),
            addy10: getNullableDataValue(data.addy10, ''),
            accMngId: getNullableDataValue(data.accMngId, ''),
            mngId: getNullableDataValue(data.mngId, ''),
            areaMngId: getNullableDataValue(data.areaMngId, ''),
            regiMngId: getNullableDataValue(data.regiMngId, ''),
            vicepId: getNullableDataValue(data.vicepId, ''),
            admin: getNullableDataValue(data.admin, ''),
            supAdmin: getNullableDataValue(data.supAdmin, ''),
            globAdmin: getNullableDataValue(data.globAdmin, ''),
            miscInput: getNullableDataValue(data.miscInput, ''),
        });
    }
}
