export const TransType = {
    Qualifying: 'Law 1Qualifying',
    Law_Ada_Ab: 'Law ADA AB',
    Law_Ada_Other: 'Law ADA Other',
    Law_Ada_Web: 'Law ADA Web',
    Law_Adar: 'Law ADAR',
    Law_Fdcpa: 'Law FDCPA',
    Law_GenLit: 'Law GenLit',
    Law_Hourly: 'Law Hourly',
    Law_Hr_LenderLit: 'Law HR LenderLit',
    Law_Hr_LenderLit_IL: 'Law HR LenderLit IL',
    Law_Hr_LoanMod: 'Law HR LoanMod',
    Law_P65: 'Law P65',
    Law_Pi: 'Law PI',
    Law_Tcpa: 'Law TCPA',
    Other: '',
};
