import { Component, OnInit, Input } from '@angular/core';
import { FormGroup, FormBuilder } from '@angular/forms';
import { Observable } from 'rxjs';
import { ContactService } from '../../../../@core/backend/common/services/contact.service';
import { getNullableDataValue, getNullableDateValue } from '../../../../@core/utils/helpers';

@Component({
    selector: 'ngx-sales-com',
    templateUrl: './sales-com.component.html',
    styleUrls: ['./sales-com.component.scss'],
})
export class SalesComComponent implements OnInit {
    accountName: '';
    form: FormGroup;
    @Input() service: ContactService;
    @Input() data: Observable<any>;

    constructor(private fb: FormBuilder) { }

    ngOnInit() {
        this.form = this.initForm(this.fb);
        this.loadAccountTestData(this.form);
    }

    loadAccountTestData(form: FormGroup) {
        const data = {
            estPropV: 'est Prop Value',
            occup: 'Occupancy',
            propType: 'propType',
            originalP: 'Orginal Price',
            retention: 'Retention',
            lastRefiDate: new Date,
            notes: 'Notes',
            firstLien: '1st lien',
            firstLien2: 'Payment',
            firstLien3: 'Rate',
            loanType1: 'Loan Type',
            lender1: 'Lender',
            secondLien: '2nd Lien',
            secondLien2: 'Payment',
            secondLien3: 'Rate',
            loanType2: 'loanType',
            lender2: 'Lender',
            thirdLien: '3rd Lien',
            thirdLien2: 'Payment',
            thirdLien3: 'Rate',
            loanType3: 'Loan Type',
            lender3: 'Lender',
            cashout4: 'Cash Out',
            taxes: 'taxes',
            ccMisc: 'CC-Misc',
            insurHOA: 'insurance HOA',
            pmiMi: 'PMI-MI',
            floodInsur: 'Flood Insurance',
            creditReport: 'Credit Report #',
            lastrepDate: new Date,
            total1: 'Total',
            approxPrice: 'Approx Price',
            maxDownPmt: 'Max Down Pmt',
            maxMoPmt: 'Max Mo. Pmt',
            time2Buy: 'Time to Buy',
            rentCurrentRes: 'Rent / Current Res.',
            rentPayment: 'Rent Payment',
            propType2: 'Prop. Type',
            approxSqFt: 'Approx Sq. Ft',
            bedNumb: 'Bed Number',
            bathNumb: 'Bath Number',
            workAgentYes: 'checkbox',
            workAgentNo: 'checkbox',
            firstBuyYes: 'checkbox',
            firstBuyNo: 'checkbox',
            coSignYes: 'checkbox',
            coSignNo: 'checkbox',
            obtGiftYes: 'checkbox',
            obtGiftNo: 'checkbox',
            creditReport2: 'Credit Report Number',
            lastrepDate2: new Date,
            ppValue: 'P.P Value',
            loanAmt: 'Loan Amount',
            ltv: 'LTV',
            downPMT: 'Down Payment',
            preAppDate: new Date,
            ppValue2: 'P.P Value',
            downPMT2: 'Down Payment',
            loanAmt2: 'Loan Amount',
            mipFF: 'MIP/FF',
            totLoanAmt: 'Total Loan Amount',
            rate5: 'Rate',
            tem: 'Tem',
            pi: 'PI',
            tx: 'TX',
            ins: 'INS',
            mi: 'MI',
            piti: 'PITI',
            dti: 'DTI',
        };
        this.setFormValues(form, data);
    }

    initForm(fb: FormBuilder): FormGroup {
        const form = fb.group({
            estPropV: fb.control(''),
            occup: fb.control(''),
            propType: fb.control(''),
            originalP: fb.control(''),
            retention: fb.control(''),
            lastRefiDate: fb.control(''),
            notes: fb.control(''),
            firstLien: fb.control(''),
            firstLien2: fb.control(''),
            firstLien3: fb.control(''),
            loanType1: fb.control(''),
            lender1: fb.control(''),
            lender3: fb.control(''),
            secondLien: fb.control(''),
            secondLien2: fb.control(''),
            secondLien3: fb.control(''),
            loanType2: fb.control(''),
            lender2: fb.control(''),
            thirdLien: fb.control(''),
            thirdLien2: fb.control(''),
            thirdLien3: fb.control(''),
            loanType3: fb.control(''),
            cashout4: fb.control(''),
            taxes: fb.control(''),
            ccMisc: fb.control(''),
            insurHOA: fb.control(''),
            pmiMi: fb.control(''),
            floodInsur: fb.control(''),
            creditReport: fb.control(''),
            lastrepDate: fb.control(''),
            total1: fb.control(''),
            approxPrice: fb.control(''),
            maxDownPmt: fb.control(''),
            maxMoPmt: fb.control(''),
            time2Buy: fb.control(''),
            rentCurrentRes: fb.control(''),
            rentPayment: fb.control(''),
            propType2: fb.control(''),
            approxSqFt: fb.control(''),
            bedNumb: fb.control(''),
            bathNumb: fb.control(''),
            workAgentYes: fb.control(''),
            workAgentNo: fb.control(''),
            firstBuyYes: fb.control(''),
            firstBuyNo: fb.control(''),
            coSignYes: fb.control(''),
            coSignNo: fb.control(''),
            obtGiftYes: fb.control(''),
            obtGiftNo: fb.control(''),
            creditReport2: fb.control(''),
            lastrepDate2: fb.control(''),
            ppValue: fb.control(''),
            loanAmt: fb.control(''),
            ltv: fb.control(''),
            downPMT: fb.control(''),
            preAppDate: fb.control(''),
            ppValue2: fb.control(''),
            downPMT2: fb.control(''),
            loanAmt2: fb.control(''),
            mipFF: fb.control(''),
            totLoanAmt: fb.control(''),
            rate5: fb.control(''),
            tem: fb.control(''),
            pi: fb.control(''),
            tx: fb.control(''),
            ins: fb.control(''),
            mi: fb.control(''),
            piti: fb.control(''),
            dti: fb.control(''),
        }, { updateOn: 'blur' });
        return form;
    }
    setFormValues(form: FormGroup, data: any) {
        form.setValue({
            occup: getNullableDataValue(data.occup, ''),
            estPropV: getNullableDataValue(data.estPropV, ''),
            propType: getNullableDataValue(data.propType, ''),
            originalP: getNullableDataValue(data.originalP, ''),
            retention: getNullableDataValue(data.retention, ''),
            lastRefiDate: getNullableDataValue(data.lastRefiDate, ''),
            notes: getNullableDataValue(data.notes, ''),
            firstLien: getNullableDataValue(data.firstLien, ''),
            firstLien2: getNullableDataValue(data.firstLien2, ''),
            firstLien3: getNullableDataValue(data.firstLien3, ''),
            loanType1: getNullableDataValue(data.loanType1, ''),
            lender1: getNullableDataValue(data.lender1, ''),
            secondLien: getNullableDataValue(data.secondLien, ''),
            secondLien2: getNullableDataValue(data.secondLien2, ''),
            secondLien3: getNullableDataValue(data.secondLien3, ''),
            loanType2: getNullableDataValue(data.loanType2, ''),
            lender2: getNullableDataValue(data.lender2, ''),
            thirdLien: getNullableDataValue(data.thirdLien, ''),
            thirdLien2: getNullableDataValue(data.thirdLien2, ''),
            thirdLien3: getNullableDataValue(data.thirdLien3, ''),
            loanType3: getNullableDataValue(data.loanType3, ''),
            lender3: getNullableDataValue(data.lender3, ''),
            cashout4: getNullableDataValue(data.cashout4, ''),
            taxes: getNullableDataValue(data.taxes, ''),
            ccMisc: getNullableDataValue(data.ccMisc, ''),
            insurHOA: getNullableDataValue(data.insurHOA, ''),
            pmiMi: getNullableDataValue(data.pmiMi, ''),
            floodInsur: getNullableDataValue(data.floodInsur, ''),
            creditReport: getNullableDataValue(data.creditReport, ''),
            lastrepDate: getNullableDateValue(data.lastrepDate, ''),
            total1: getNullableDataValue(data.total1, ''),
            approxPrice: getNullableDataValue(data.approxPrice, ''),
            maxDownPmt: getNullableDataValue(data.maxDownPmt, ''),
            maxMoPmt: getNullableDataValue(data.maxMoPmt, ''),
            time2Buy: getNullableDataValue(data.time2Buy, ''),
            rentCurrentRes: getNullableDataValue(data.rentCurrentRes, ''),
            rentPayment: getNullableDataValue(data.rentPayment, ''),
            propType2: getNullableDataValue(data.propType2, ''),
            approxSqFt: getNullableDataValue(data.approxSqFt, ''),
            bedNumb: getNullableDataValue(data.bedNumb, ''),
            bathNumb: getNullableDataValue(data.bathNumb, ''),
            workAgentYes: getNullableDataValue(data.workAgentYes, ''),
            workAgentNo: getNullableDataValue(data.workAgentNo, ''),
            firstBuyYes: getNullableDataValue(data.firstBuyYes, ''),
            firstBuyNo: getNullableDataValue(data.firstBuyNo, ''),
            coSignYes: getNullableDataValue(data.coSignYes, ''),
            coSignNo: getNullableDataValue(data.coSignNo, ''),
            obtGiftYes: getNullableDataValue(data.obtGiftYes, ''),
            obtGiftNo: getNullableDataValue(data.obtGiftNo, ''),
            creditReport2: getNullableDataValue(data.creditReport2, ''),
            lastrepDate2: getNullableDateValue(data.lastrepDate2, ''),
            ppValue: getNullableDataValue(data.ppValue, ''),
            loanAmt: getNullableDataValue(data.loanAmt, ''),
            ltv: getNullableDataValue(data.ltv, ''),
            downPMT: getNullableDataValue(data.downPMT, ''),
            preAppDate: getNullableDateValue(data.preAppDate, ''),
            ppValue2: getNullableDataValue(data.ppValue2, ''),
            downPMT2: getNullableDataValue(data.downPMT2, ''),
            loanAmt2: getNullableDataValue(data.loanAmt2, ''),
            mipFF: getNullableDataValue(data.mipFF, ''),
            totLoanAmt: getNullableDataValue(data.totLoanAmt, ''),
            rate5: getNullableDataValue(data.rate5, ''),
            tem: getNullableDataValue(data.tem, ''),
            pi: getNullableDataValue(data.pi, ''),
            tx: getNullableDataValue(data.tx, ''),
            ins: getNullableDataValue(data.ins, ''),
            mi: getNullableDataValue(data.mi, ''),
            piti: getNullableDataValue(data.piti, ''),
            dti: getNullableDataValue(data.dti, ''),
        });
    }
}
