import { Component, OnInit, Input } from '@angular/core';
import { ContactService } from '../../../../../../@core/backend/common/services/contact.service';
import { FormGroup, FormBuilder } from '@angular/forms';
import { Observable } from 'rxjs';
import { User, UserData } from '../../../../../../@core/interfaces/common/users';
import { ROLES } from '../../../../../../@auth/roles';
import { NbRoleProvider } from '@nebular/security';
import { getNullableDataValue, getNullableDateValue } from '../../../../../../@core/utils/helpers';
@Component({
    selector: 'ngx-afg-pro-tab',
    templateUrl: './afg-pro-tab.component.html',
    styleUrls: ['./afg-pro-tab.component.scss'],
})
export class AFGProTabComponent implements OnInit {

    accountName: '';
    form: FormGroup;
    users: User[] = [];
    @Input() service: ContactService;
    @Input() data: Observable<any>;

    constructor(
        private fb: FormBuilder,
        private usersService: UserData,
        private roleService: NbRoleProvider,

    ) { }

    ngOnInit(): void {
        this.roleService.getRole().subscribe(r => {
            if (r.includes(ROLES.ADMIN)) {
                this.usersService.list(1, 90000).subscribe(u => {
                    const items: User[] = u.items;
                    this.users = items.sort((a, b) => {
                        if (a.lastName > b.lastName) {
                            return -1;
                        }
                        if (b.lastName > a.lastName) {
                            return 1;
                        }
                        if (b.lastName === a.lastName) {
                            if (a.firstName > b.firstName) {
                                return -1;
                            }
                            if (b.firstName > a.firstName) {
                                return 1;
                            }
                        }
                        return 0;
                    });
                });
            }
        });
        this.form = this.initForm(this.fb);
        this.loadAccountTestData(this.form);

    }

    loadAccountData(form: any, response: any) {
        response.subscribe((data) => {
            this.setFormValues(form, data);
        });
    }

    loadAccountTestData(form: any) {
        const data = {
            estCloseDt: new Date(),
            cocReqDt: new Date(),
            lend: 'Lender',
            lnAmt: 'Loan Amount',
            lnPgrm: 'Loan Program',
            lendLn: 'Lender Loan #',
            impnd: 'Impounds',
            lockDt: new Date(),
            rtXpDt: new Date(),
            rtPrce: 'Rate / Price',
            apprsOrd: new Date(),
            ppEstV: 'P.P/Est Value',
            apprsRcvd: new Date(),
            apprsV: 'Appraisal Value',
            ntProc: 'Processing Update Notes',
            ntOrig: 'Originators Notes',
            ntPm: 'P.M. /Loan Coordinator Notes',
            ntProcDt: new Date(),
            ntOrigDt: new Date(),
            ntPmDt: new Date(),
            lnIssNt: 'Loan Issure Notes',
            mgmtSpCb: 'Management Support',
            sbmnNt: 'Submission Notes/ Loan Goals:',
            cnd1B: 'B',
            cnd1E: 'E',
            cnd1T: 'T',
            cnd1A: 'A',
            cndSlct: 'select',
            cnd1P: 'P',
            cnd1L: 'L',
            cndDt: new Date(),
            cndRcvdDt: new Date(),
            clr: 'Clear',
            cnd2B: 'B',
            cnd2E: 'E',
            cnd2T: 'T',
            cnd2A: 'A',
            cndSlct2: 'select',
            cnd2P: 'P',
            cnd2L: 'L',
            cndDt2: new Date(),
            cndRcvdDt2: new Date(),
            clr2: 'clear',
            cnd3B: 'B',
            cnd3E: 'E',
            cnd3T: 'T',
            cnd3A: 'A',
            cndSlct3: 'select',
            cnd3P: 'P',
            cnd3L: 'L',
            cndDt3: new Date(),
            cndRcvdDt3: new Date(),
            clr3: 'clear',
            cnd4B: 'B',
            cnd4E: 'E',
            cnd4T: 'T',
            cnd4A: 'A',
            cndSlct4: 'select',
            cnd4P: 'P',
            cnd4L: 'L',
            cndDt4: new Date(),
            cndRcvdDt4: new Date(),
            clr4: 'clear',
            cnd5B: 'B',
            cnd5E: 'E',
            cnd5T: 'T',
            cnd5A: 'A',
            cndSlct5: 'select',
            cnd5P: 'P',
            cnd5L: 'L',
            cndDt5: new Date(),
            cndRcvdDt5: new Date(),
            clr5: 'clear',
            cnd6B: 'B',
            cnd6E: 'E',
            cnd6T: 'T',
            cnd6A: 'A',
            cndSlct6: 'select',
            cnd6P: 'P',
            cnd6L: 'L',
            cndDt6: new Date(),
            cndRcvdDt6: new Date(),
            clr6: 'clear',
            cnd7B: 'B',
            cnd7E: 'E',
            cnd7T: 'T',
            cnd7A: 'A',
            cndSlct7: 'select',
            cnd7P: 'P',
            cnd7L: 'L',
            cndDt7: new Date(),
            cndRcvdDt7: new Date(),
            clr7: 'clear',
            cnd8B: 'B',
            cnd8E: 'E',
            cnd8T: 'T',
            cnd8A: 'A',
            cndSlct8: 'select',
            cnd8P: 'P',
            cnd8L: 'L',
            cndDt8: new Date(),
            cndRcvdDt8: new Date(),
            clr8: 'clear',
            cnd9B: 'B',
            cnd9E: 'E',
            cnd9T: 'T',
            cnd9A: 'A',
            cndSlct9: 'select',
            cnd9P: 'P',
            cnd9L: 'L',
            cndDt9: new Date(),
            cndRcvdDt9: new Date(),
            clr9: 'clear',
            cnd10B: 'B',
            cnd10E: 'E',
            cnd10T: 'T',
            cnd10A: 'A',
            cndSlct10: 'select',
            cnd10P: 'P',
            cnd10L: 'L',
            cndDt10: new Date(),
            cndRcvdDt10: new Date(),
            clr10: 'clear',
        };
        this.setFormValues(form, data);
    }

    setFormValues(form: any, data: any) {
        form.setValue({
            estCloseDt: getNullableDateValue(data.estCloseDt, ''),
            cocReqDt: getNullableDateValue(data.cocReqDt, ''),
            lend: getNullableDataValue(data.lend, ''),
            lnAmt: getNullableDataValue(data.lnAmt, ''),
            lnPgrm: getNullableDataValue(data.lnPgrm, ''),
            lendLn: getNullableDataValue(data.lendLn, ''),
            impnd: getNullableDataValue(data.impnd, ''),
            lockDt: getNullableDateValue(data.lockDt, ''),
            rtXpDt: getNullableDateValue(data.rtXpDt, ''),
            rtPrce: getNullableDataValue(data.rtPrce, ''),
            apprsOrd: getNullableDateValue(data.apprsOrd, ''),
            ppEstV: getNullableDataValue(data.ppEstV, ''),
            apprsRcvd: getNullableDataValue(data.apprsRcvd, ''),
            apprsV: getNullableDataValue(data.apprsV, ''),
            ntProc: getNullableDataValue(data.ntProc, ''),
            ntOrig: getNullableDataValue(data.ntOrig, ''),
            ntPm: getNullableDataValue(data.ntPm, ''),
            ntProcDt: getNullableDateValue(data.ntProcDt, ''),
            ntOrigDt: getNullableDateValue(data.ntOrigDt, ''),
            ntPmDt: getNullableDateValue(data.ntPmDt, ''),
            lnIssNt: getNullableDataValue(data.lnIssNt, ''),
            mgmtSpCb: getNullableDataValue(data.mgmtSpCb, ''),
            sbmnNt: getNullableDataValue(data.sbmnNt, ''),
            cnd1B: getNullableDataValue(data.cnd1B, ''),
            cnd1E: getNullableDataValue(data.cnd1E, ''),
            cnd1T: getNullableDataValue(data.cnd1T, ''),
            cnd1A: getNullableDataValue(data.cnd1A, ''),
            cndSlct: getNullableDataValue(data.cndSlct, ''),
            cnd1P: getNullableDataValue(data.cnd1P, ''),
            cnd1L: getNullableDataValue(data.cnd1L, ''),
            cndDt: getNullableDateValue(data.cndDt, ''),
            cndRcvdDt: getNullableDateValue(data.cndRcvdDt, ''),
            clr: getNullableDataValue(data.clr, ''),
            cnd2B: getNullableDataValue(data.cnd2B, ''),
            cnd2E: getNullableDataValue(data.cnd2E, ''),
            cnd2T: getNullableDataValue(data.cnd2T, ''),
            cnd2A: getNullableDataValue(data.cnd2A, ''),
            cndSlct2: getNullableDataValue(data.cndSlct2, ''),
            cnd2P: getNullableDataValue(data.cnd2P, ''),
            cnd2L: getNullableDataValue(data.cnd2L, ''),
            cndDt2: getNullableDateValue(data.cndDt2, ''),
            cndRcvdDt2: getNullableDateValue(data.cndRcvdDt2, ''),
            clr2: getNullableDataValue(data.clr2, ''),
            cnd10E: getNullableDataValue(data.cnd10E, ''),
            cnd3B: getNullableDataValue(data.cnd3B, ''),
            cnd3E: getNullableDataValue(data.cnd3E, ''),
            cnd3T: getNullableDataValue(data.cnd3T, ''),
            cnd3A: getNullableDataValue(data.cnd3A, ''),
            cndSlct3: getNullableDataValue(data.cndSlct3, ''),
            cnd3P: getNullableDataValue(data.cnd3P, ''),
            cnd3L: getNullableDataValue(data.cnd3L, ''),
            cndDt3: getNullableDateValue(data.cndDt3, ''),
            cndRcvdDt3: getNullableDateValue(data.cndRcvdDt3, ''),
            clr3: getNullableDataValue(data.clr3, ''),
            cnd4B: getNullableDataValue(data.cnd4B, ''),
            cnd4E: getNullableDataValue(data.cnd4E, ''),
            cnd4T: getNullableDataValue(data.cnd4T, ''),
            cnd4A: getNullableDataValue(data.cnd4A, ''),
            cndSlct4: getNullableDataValue(data.cndSlct4, ''),
            cnd4P: getNullableDataValue(data.cnd4P, ''),
            cnd4L: getNullableDataValue(data.cnd4L, ''),
            cndDt4: getNullableDateValue(data.cndDt4, ''),
            cndRcvdDt4: getNullableDateValue(data.cndRcvdDt4, ''),
            clr4: getNullableDataValue(data.clr4, ''),
            cnd5B: getNullableDataValue(data.cnd5B, ''),
            cnd5E: getNullableDataValue(data.cnd5E, ''),
            cnd5T: getNullableDataValue(data.cnd5T, ''),
            cnd5A: getNullableDataValue(data.cnd5A, ''),
            cndSlct5: getNullableDataValue(data.cndSlct5, ''),
            cnd5P: getNullableDataValue(data.cnd5P, ''),
            cnd5L: getNullableDataValue(data.cnd5L, ''),
            cndDt5: getNullableDataValue(data.cndDt5, ''),
            cndRcvdDt5: getNullableDateValue(data.cndRcvdDt5, ''),
            clr5: getNullableDataValue(data.clr5, ''),
            cnd6B: getNullableDataValue(data.cnd6B, ''),
            cnd6E: getNullableDataValue(data.cnd6E, ''),
            cnd6T: getNullableDataValue(data.cnd6T, ''),
            cnd6A: getNullableDataValue(data.cnd6A, ''),
            cndSlct6: getNullableDataValue(data.cndSlct6, ''),
            cnd6P: getNullableDataValue(data.cnd6P, ''),
            cnd6L: getNullableDataValue(data.cnd6L, ''),
            cndDt6: getNullableDateValue(data.cndDt6, ''),
            cndRcvdDt6: getNullableDateValue(data.cndRcvdDt6, ''),
            clr6: getNullableDataValue(data.clr6, ''),
            cnd7B: getNullableDataValue(data.cnd7B, ''),
            cnd7E: getNullableDataValue(data.cnd7E, ''),
            cnd7T: getNullableDataValue(data.cnd7T, ''),
            cnd7A: getNullableDataValue(data.cnd7A, ''),
            cndSlct7: getNullableDataValue(data.cndSlct7, ''),
            cnd7P: getNullableDataValue(data.cnd7P, ''),
            cnd7L: getNullableDataValue(data.cnd7L, ''),
            cndDt7: getNullableDateValue(data.cndDt7, ''),
            cndRcvdDt7: getNullableDateValue(data.cndRcvdDt7, ''),
            clr7: getNullableDataValue(data.clr7, ''),
            cnd8B: getNullableDataValue(data.cnd8B, ''),
            cnd8E: getNullableDataValue(data.cnd8E, ''),
            cnd8T: getNullableDataValue(data.cnd8T, ''),
            cnd8A: getNullableDataValue(data.cnd8A, ''),
            cndSlct8: getNullableDataValue(data.cndSlct8, ''),
            cnd8P: getNullableDataValue(data.cnd8P, ''),
            cnd8L: getNullableDataValue(data.cnd8L, ''),
            cndDt8: getNullableDateValue(data.cndDt8, ''),
            cndRcvdDt8: getNullableDateValue(data.cndRcvdDt8, ''),
            clr8: getNullableDataValue(data.clr8, ''),
            cnd9B: getNullableDataValue(data.cnd9B, ''),
            cnd9E: getNullableDataValue(data.cnd9E, ''),
            cnd9T: getNullableDataValue(data.cnd9T, ''),
            cnd9A: getNullableDataValue(data.cnd9A, ''),
            cndSlct9: getNullableDataValue(data.cndSlct9, ''),
            cnd9P: getNullableDataValue(data.cnd9P, ''),
            cnd9L: getNullableDataValue(data.cnd9L, ''),
            cndDt9: getNullableDateValue(data.cndDt9, ''),
            cndRcvdDt9: getNullableDateValue(data.cndDt10, ''),
            clr9: getNullableDataValue(data.clr9, ''),
            cnd10B: getNullableDataValue(data.cnd10B, ''),
            cnd10T: getNullableDataValue(data.cnd10T, ''),
            cnd10A: getNullableDataValue(data.cnd10A, ''),
            cndSlct10: getNullableDataValue(data.cndSlct10, ''),
            cnd10P: getNullableDataValue(data.cnd10P, ''),
            cnd10L: getNullableDataValue(data.cnd10L, ''),
            cndDt10: getNullableDateValue(data.cndDt10, ''),
            cndRcvdDt10: getNullableDateValue(data.cndRcvdDt10, ''),
            clr10: getNullableDataValue(data.clr10, ''),
        });
    }

    initForm(fb: any): any {

        const form = fb.group({
            cndRcvdDt6: fb.control(''),
            estCloseDt: fb.control(''),
            cocReqDt: fb.control(''),
            lend: fb.control(''),
            lnAmt: fb.control(''),
            lnPgrm: fb.control(''),
            lendLn: fb.control(''),
            impnd: fb.control(''),
            lockDt: fb.control(''),
            rtXpDt: fb.control(''),
            rtPrce: fb.control(''),
            apprsOrd: fb.control(''),
            ppEstV: fb.control(''),
            apprsRcvd: fb.control(''),
            apprsV: fb.control(''),
            ntProc: fb.control(''),
            ntOrig: fb.control(''),
            ntPm: fb.control(''),
            ntProcDt: fb.control(''),
            ntOrigDt: fb.control(''),
            ntPmDt: fb.control(''),
            lnIssNt: fb.control(''),
            mgmtSpCb: fb.control(''),
            sbmnNt: fb.control(''),
            cnd1B: fb.control(''),
            cnd1E: fb.control(''),
            cnd1T: fb.control(''),
            cnd1A: fb.control(''),
            cndSlct: fb.control(''),
            cnd1P: fb.control(''),
            cnd1L: fb.control(''),
            cndDt: fb.control(''),
            cndRcvdDt: fb.control(''),
            clr: fb.control(''),
            cnd2B: fb.control(''),
            cnd2E: fb.control(''),
            cnd2T: fb.control(''),
            cnd2A: fb.control(''),
            cndSlct2: fb.control(''),
            cnd2P: fb.control(''),
            cnd2L: fb.control(''),
            cndDt2: fb.control(''),
            cndRcvdDt2: fb.control(''),
            clr2: fb.control(''),
            cnd3B: fb.control(''),
            cnd3E: fb.control(''),
            cnd3T: fb.control(''),
            cnd3A: fb.control(''),
            cndSlct3: fb.control(''),
            cnd3P: fb.control(''),
            cnd3L: fb.control(''),
            cndDt3: fb.control(''),
            cndRcvdDt3: fb.control(''),
            clr3: fb.control(''),
            cnd4B: fb.control(''),
            cnd4E: fb.control(''),
            cnd4T: fb.control(''),
            cnd4A: fb.control(''),
            cndSlct4: fb.control(''),
            cnd4P: fb.control(''),
            cnd4L: fb.control(''),
            cndDt4: fb.control(''),
            cndRcvdDt4: fb.control(''),
            clr4: fb.control(''),
            cnd5B: fb.control(''),
            cnd5E: fb.control(''),
            cnd5T: fb.control(''),
            cnd5A: fb.control(''),
            cndSlct5: fb.control(''),
            cnd5P: fb.control(''),
            cnd5L: fb.control(''),
            cndDt5: fb.control(''),
            cndRcvdDt5: fb.control(''),
            clr5: fb.control(''),
            cnd6B: fb.control(''),
            cnd6E: fb.control(''),
            cnd6T: fb.control(''),
            cnd6A: fb.control(''),
            cndSlct6: fb.control(''),
            cnd6P: fb.control(''),
            cnd6L: fb.control(''),
            cndDt6: fb.control(''),
            clr6: fb.control(''),
            cnd7B: fb.control(''),
            cnd7E: fb.control(''),
            cnd7T: fb.control(''),
            cnd7A: fb.control(''),
            cndSlct7: fb.control(''),
            cnd7P: fb.control(''),
            cnd7L: fb.control(''),
            cndDt7: fb.control(''),
            cndRcvdDt7: fb.control(''),
            clr7: fb.control(''),
            cnd8B: fb.control(''),
            cnd8E: fb.control(''),
            cnd8T: fb.control(''),
            cnd8A: fb.control(''),
            cndSlct8: fb.control(''),
            cnd8P: fb.control(''),
            cnd8L: fb.control(''),
            cndDt8: fb.control(''),
            cndRcvdDt8: fb.control(''),
            clr8: fb.control(''),
            cnd9B: fb.control(''),
            cnd9E: fb.control(''),
            cnd9T: fb.control(''),
            cnd9A: fb.control(''),
            cndSlct9: fb.control(''),
            cnd9P: fb.control(''),
            cnd9L: fb.control(''),
            cndDt9: fb.control(''),
            cndRcvdDt9: fb.control(''),
            clr9: fb.control(''),
            cnd10B: fb.control(''),
            cnd10E: fb.control(''),
            cnd10T: fb.control(''),
            cnd10A: fb.control(''),
            cndSlct10: fb.control(''),
            cnd10P: fb.control(''),
            cnd10L: fb.control(''),
            cndDt10: fb.control(''),
            cndRcvdDt10: fb.control(''),
            clr10: fb.control(''),
        }, { updateOn: 'blur' });
        return form;
    }
}
